

#############################################################################
# Module:           Operator
# Module Desc:      Lots of Operators
# Project:          Pathan, Open Source X-Path module for Xerces C++
# Project Version:  1
# tmake Template:   pathanSubdir
# Creation Date:    14:44, 2001/09/28
#############################################################################

###### Include macro definitions

MAKEDEFS = ../../Makefile.defs
include $(MAKEDEFS)

###### Files

SOURCES     = And.cpp \
              Or.cpp \
              Intersect.cpp \
              Except.cpp \
              Divide.cpp \
              IntegerDivide.cpp \
              Equals.cpp \
              GreaterThan.cpp \
              GreaterThanEqual.cpp \
              LessThan.cpp \
              LessThanEqual.cpp \
              Minus.cpp \
              Mod.cpp \
              Multiply.cpp \
              NotEquals.cpp \
              Plus.cpp \
              Range.cpp \
              UnaryMinus.cpp \
              Union.cpp \
              NodeComparison.cpp \
              OrderComparison.cpp \
              TotalOrderComparison.cpp \
              GeneralComp.cpp \
							ArithmeticOperator.cpp \
							ComparisonOperator.cpp

###### Include rules

RULES = ../../Makefile.rules
include $(RULES)
