

#############################################################################
# Module:           Items
# Module Desc:      XPath2 Datatypes
# Project:          Pathan, Open Source X-Path module for Xerces C++
# Project Version:  1
# tmake Template:   pathanSubdir
# Creation Date:    15:42, 2003/04/30
#############################################################################

###### Include macro definitions

MAKEDEFS = ../../Makefile.defs
include $(MAKEDEFS)

###### Files

SOURCES     =   Item.cpp \
                AnyAtomicType.cpp \
                ATDurationOrDerived.cpp \
                ATUntypedAtomic.cpp \
                Node.cpp \
                Numeric.cpp \
                Timezone.cpp \
                DateOrTimeType.cpp \
								ReferenceCounted.cpp \
								AnyAtomicTypeConstructor.cpp \
								ATQNameConstructor.cpp

###### Include rules

RULES = ../../Makefile.rules
include $(RULES)
