# $Id: Makefile,v 1.3 2005/07/27 17:56:05 gmf Exp $

###### Include macro definitions

MAKEDEFS = ../../../build_unix/Makefile.defs
include $(MAKEDEFS)

###### Files

SOURCES= $(SHELL_SOURCES)

###### Include rules

RULES = ../../../build_unix/Makefile.rules
include $(RULES)



