#include "System/ConfigProperties.cpp"
#include "System/PlatformInit.cpp"
#include "System/TimerUtil.cpp"

#include "Exception/AliasNotFoundException.cpp"
#include "Exception/ConnectionFailedException.cpp"
#include "Exception/DuplicateParameterException.cpp"
#include "Exception/DwfException.cpp"
#include "Exception/DwfSectionNotFoundException.cpp"
#include "Exception/DwfSectionResourceNotFoundException.cpp"
#include "Exception/InvalidDwfPackageException.cpp"
#include "Exception/InvalidDwfSectionException.cpp"
#include "Exception/InvalidFeatureSourceException.cpp"
#include "Exception/InvalidPrintLayoutFontSizeUnitsException.cpp"
#include "Exception/InvalidPrintLayoutPositionUnitsException.cpp"
#include "Exception/InvalidPrintLayoutSizeUnitsException.cpp"
#include "Exception/ParameterNotFoundException.cpp"
#include "Exception/StylizeLayerFailedException.cpp"

#include "MapLayer/Layer.cpp"
#include "MapLayer/Map.cpp"
#include "MapLayer/Selection.cpp"

#include "Services/ByteSourceRasterStreamImpl.cpp"
#include "Services/DataReader.cpp"
#include "Services/DrawingService.cpp"
#include "Services/FeatureReader.cpp"
#include "Services/FeatureService.cpp"
#include "Services/ImageFormats.cpp"
#include "Services/ProfilingService.cpp"
#include "Services/RenderingService.cpp"
#include "Services/ResourceService.cpp"
#include "Services/ScrollableFeatureReader.cpp"
#include "Services/ServiceFactory.cpp"
#include "Services/SqlReader.cpp"
#include "Services/TileService.cpp"
#include "Services/Transaction.cpp"

#include "Services/Drawing/DrawingServiceUtil.cpp"

#include "Services/Feature/CreateFeatureSource.cpp"
#include "Services/Feature/FdoConnectionPool.cpp"
#include "Services/Feature/FdoConnectionUtil.cpp"
#include "Services/Feature/FdoForcedOneToOneFeatureReader.cpp"
#include "Services/Feature/FeatureClassCacheItem.cpp"
#include "Services/Feature/FeatureConnection.cpp"
#include "Services/Feature/FeatureSchemaCacheItem.cpp"
#include "Services/Feature/FeatureServiceCacheEntry.cpp"
#include "Services/Feature/FeatureServiceCache.cpp"
#include "Services/Feature/FeatureSourceCacheItem.cpp"
#include "Services/Feature/FeatureUtil.cpp"
#include "Services/Feature/GwsConnectionPool.cpp"
#include "Services/Feature/GwsFeatureReader.cpp"
#include "Services/Feature/JoinFeatureReader.cpp"
#include "Services/Feature/MgCSTrans.cpp"
#include "Services/Feature/ProjectedFeatureReader.cpp"
#include "Services/Feature/RasterHelper.cpp"
#include "Services/Feature/RdbmsFeatureSourceParams.cpp"
#include "Services/Feature/SpatialContextCacheItem.cpp"
#include "Services/Feature/TransformCache.cpp"

#include "Services/Rendering/CustomLogoInfo.cpp"
#include "Services/Rendering/CustomTextInfo.cpp"
#include "Services/Rendering/DwfVersion.cpp"
#include "Services/Rendering/FeatureInfoRenderer.cpp"
#include "Services/Rendering/Layout.cpp"
#include "Services/Rendering/LegendPlotUtil.cpp"
#include "Services/Rendering/MappingUtil.cpp"
#include "Services/Rendering/MapPlot.cpp"
#include "Services/Rendering/MapPlotCollection.cpp"
#include "Services/Rendering/PrintLayout.cpp"
#include "Services/Rendering/PlotSpecification.cpp"
#include "Services/Rendering/RenderingOptions.cpp"
#include "Services/Rendering/RSMgFeatureReader.cpp"
#include "Services/Rendering/RSMgRaster.cpp"
#include "Services/Rendering/RSMgSymbolManager.cpp"
#include "Services/Rendering/UnitType.cpp"

#include "Services/Resource/ByteSourceDwfInputStreamImpl.cpp"
#include "Services/Resource/OperationInfo.cpp"
#include "Services/Resource/OperationParameter.cpp"
#include "Services/Resource/ResourceDefs.cpp"
#include "Services/Resource/ResourcePackageHandler.cpp"
#include "Services/Resource/ResourcePackageLoader.cpp"
#include "Services/Resource/ResourcePackageManifestHandler.cpp"
#include "Services/Resource/ResourcePackageManifestParser.cpp"
#include "Services/Resource/UnmanagedDataManager.cpp"
#include "Services/Resource/UnmanagedDataType.cpp"
#include "Services/Resource/ZipFileHandler.cpp"
#include "Services/Resource/ZipFileReader.cpp"

#include "Services/Stylization/SEMgSymbolManager.cpp"

#include "Services/Tile/TileDefs.cpp"
#include "Services/Tile/TileCache.cpp"