

#############################################################################
# Module:           DataItem
# Module Desc:      Data Item Module
# Project:          Pathan, Open Source X-Path module for Xerces C++
# Project Version:  1
# tmake Template:   pathanSubdir
# Creation Date:    14:44, 2001/09/28
#############################################################################

###### Include macro definitions

MAKEDEFS = ../../Makefile.defs
include $(MAKEDEFS)

###### Files

SOURCES     = \
    DataItemImpl.cpp \
    DataItemSequence.cpp \
    DataItemParenthesizedExpr.cpp \
    DataItemFunction.cpp \
    DataItemNav.cpp \
    DataItemVariable.cpp \
    DataItemLiteral.cpp \
    DataItemStep.cpp \
    DataItemIf.cpp \
    DataItemCastableAs.cpp \
    DataItemCastAs.cpp \
    DataItemFor.cpp \
    DataItemInstanceOf.cpp \
    DataItemQuantifiedExpr.cpp \
    DataItemTreatAs.cpp \
    DataItemOperator.cpp \
    DataItemContextItem.cpp \
    StaticResolutionContext.cpp \
		Result.cpp \
		ResultImpl.cpp \
		SingleResult.cpp \
		SequenceResult.cpp \
		EmptyResult.cpp \
		AtomizeResult.cpp \
		LazySequenceResult.cpp \
		SortIntoDocumentOrderResult.cpp \
		ResultBuffer.cpp \
		ResultBufferImpl.cpp

###### Include rules

RULES = ../../Makefile.rules
include $(RULES)
