//
//  Copyright (C) 2004-2008 by Autodesk, Inc.
//
//  This library is free software; you can redistribute it and/or
//  modify it under the terms of version 2.1 of the GNU Lesser
//  General Public License as published by the Free Software Foundation.
//
//  This library is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
//  Lesser General Public License for more details.
//
//  You should have received a copy of the GNU Lesser General Public
//  License along with this library; if not, write to the Free Software
//  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
//

#include  "Controller/Controller.cpp"
#include  "Controller/DwfController.cpp"
#include  "Controller/HtmlController.cpp"
#include  "Exception/AllProviderConnectionsUsedException.cpp"
#include  "Exception/AuthenticationFailedException.cpp"
#include  "Exception/ConnectionFailedException.cpp"
#include  "Exception/ConnectionNotOpenException.cpp"
#include  "Exception/DbException.cpp"
#include  "Exception/DbXmlException.cpp"
#include  "Exception/DuplicateGroupException.cpp"
#include  "Exception/DuplicateNameException.cpp"
#include  "Exception/DuplicateParameterException.cpp"
#include  "Exception/DuplicateRepositoryException.cpp"
#include  "Exception/DuplicateRoleException.cpp"
#include  "Exception/DuplicateServerException.cpp"
#include  "Exception/DuplicateSessionException.cpp"
#include  "Exception/DuplicateUserException.cpp"
#include  "Exception/DwfException.cpp"
#include  "Exception/DwfSectionNotFoundException.cpp"
#include  "Exception/DwfSectionResourceNotFoundException.cpp"
#include  "Exception/EndOfStreamException.cpp"
#include  "Exception/EvaluationExpiredException.cpp"
#include  "Exception/GroupNotFoundException.cpp"
#include  "Exception/InvalidDwfPackageException.cpp"
#include  "Exception/InvalidDwfSectionException.cpp"
#include  "Exception/InvalidFeatureSourceException.cpp"
#include  "Exception/InvalidIpAddressException.cpp"
#include  "Exception/InvalidLicenseException.cpp"
#include  "Exception/InvalidLogEntryException.cpp"
#include  "Exception/InvalidOperationVersionException.cpp"
#include  "Exception/InvalidPasswordException.cpp"
#include  "Exception/InvalidPrintLayoutFontSizeUnitsException.cpp"
#include  "Exception/InvalidPrintLayoutPositionUnitsException.cpp"
#include  "Exception/InvalidPrintLayoutSizeUnitsException.cpp"
#include  "Exception/InvalidSerialNumberException.cpp"
#include  "Exception/InvalidServerNameException.cpp"
#include  "Exception/LicenseException.cpp"
#include  "Exception/LicenseExpiredException.cpp"
#include  "Exception/LogOpenFailedException.cpp"
#include  "Exception/OperationProcessingException.cpp"
#include  "Exception/ParameterNotFoundException.cpp"
#include  "Exception/PathTooLongException.cpp"
#include  "Exception/PermissionDeniedException.cpp"
#include  "Exception/PortNotAvailableException.cpp"
#include  "Exception/PrintToScaleModeNotSelectedException.cpp"
#include  "Exception/RasterTransformationNotSupportedException.cpp"
#include  "Exception/RepositoryCreationFailedException.cpp"
#include  "Exception/RepositoryNotFoundException.cpp"
#include  "Exception/RepositoryNotOpenException.cpp"
#include  "Exception/RepositoryOpenFailedException.cpp"
#include  "Exception/RoleNotFoundException.cpp"
#include  "Exception/ServerNotFoundException.cpp"
#include  "Exception/ServerNotOnlineException.cpp"
#include  "Exception/SessionExpiredException.cpp"
#include  "Exception/SessionNotFoundException.cpp"
#include  "Exception/StylizeLayerFailedException.cpp"
#include  "Exception/UnauthorizedAccessException.cpp"
#include  "Exception/UnsupportedProviderThreadModelException.cpp"
#include  "Exception/UriFormatException.cpp"
#include  "MapLayer/Layer.cpp"
#include  "MapLayer/Map.cpp"
#include  "MapLayer/Selection.cpp"
#include  "Net/IOperationHandler.cpp"
#include  "Services/Command.cpp"
#include  "Services/ConnectionProperties.cpp"
#include  "Services/CustomLogoInfo.cpp"
#include  "Services/CustomTextInfo.cpp"
#include  "Services/DrawingDefs.cpp"
#include  "Services/DrawingService.cpp"
#include  "Services/DwfVersion.cpp"
#include  "Services/FeatureInformation.cpp"
#include  "Services/ImageFormats.cpp"
#include  "Services/KmlDefs.cpp"
#include  "Services/KmlService.cpp"
#include  "Services/Layout.cpp"
#include  "Services/MappingDefs.cpp"
#include  "Services/MappingService.cpp"
#include  "Services/MapPlot.cpp"
#include  "Services/MapPlotCollection.cpp"
#include  "Services/PackageStatusInformation.cpp"
#include  "Services/PlotSpecification.cpp"
#include  "Services/PrintLayout.cpp"
#include  "Services/ProxyDataReader.cpp"
#include  "Services/ProxyDrawingService.cpp"
#include  "Services/ProxyFeatureReader.cpp"
#include  "Services/ProxyFeatureService.cpp"
#include  "Services/ProxyGwsFeatureReader.cpp"
#include  "Services/ProxyKmlService.cpp"
#include  "Services/ProxyMappingService.cpp"
#include  "Services/ProxyRenderingService.cpp"
#include  "Services/ProxyResourceService.cpp"
#include  "Services/ProxySqlDataReader.cpp"
#include  "Services/ProxyTileService.cpp"
#include  "Services/RenderingDefs.cpp"
#include  "Services/RenderingOptions.cpp"
#include  "Services/RenderingService.cpp"
#include  "Services/ServerAdmin.cpp"
#include  "Services/ServerAdminDefs.cpp"
#include  "Services/ServerConnection.cpp"
#include  "Services/ServerConnectionImp.cpp"
#include  "Services/ServerConnectionPool.cpp"
#include  "Services/ServerConnectionStack.cpp"
#include  "Services/ServerInformation.cpp"
#include  "Services/Site.cpp"
#include  "Services/SiteManager.cpp"
#include  "Services/SiteInfo.cpp"
#include  "Services/SiteConnection.cpp"
#include  "Services/TileDefs.cpp"
#include  "Services/TileService.cpp"
#include  "Services/UnitType.cpp"
#include  "System/ConfigProperties.cpp"
#include  "System/MapGuideCommonFactory.cpp"
#include  "System/MapGuideStream.cpp"
#include  "System/UserInformation.cpp"
#include  "System/CryptographyManager.cpp"
#include  "Util/IpUtil.cpp"
