# $Id: Makefile,v 1.3 2006/06/13 19:32:51 gmf Exp $

###### Include macro definitions

MAKEDEFS = $(builddir)/Makefile.defs
include $(MAKEDEFS)

###### Files

SOURCES= $(DBXML_DATAITEM_SOURCES)

###### Include rules

RULES = $(builddir)/Makefile.rules
include $(RULES)
