/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sleepycat.dbxml;

import com.sleepycat.db.*;
import com.sleepycat.db.internal.DbEnv;
import com.sleepycat.db.internal.DbConstants;

public class XmlResolver {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected XmlResolver(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XmlResolver obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() /* no exception */ {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      dbxml_javaJNI.delete_XmlResolver(swigCPtr);
    }
    swigCPtr = 0;
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() throws XmlException {
    swigCMemOwn = false;
    dbxml_javaJNI.XmlResolver_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() throws XmlException {
    swigCMemOwn = true;
    dbxml_javaJNI.XmlResolver_change_ownership(this, swigCPtr, true);
  }

  protected XmlResolver() {
    this(dbxml_javaJNI.new_XmlResolver(), true);
    dbxml_javaJNI.XmlResolver_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public boolean resolveDocument(XmlTransaction txn, XmlManager mgr, String uri, XmlValue reslt) throws XmlException {
    return dbxml_javaJNI.XmlResolver_resolveDocument(swigCPtr, XmlTransaction.getCPtr(txn), XmlManager.getCPtr(mgr), uri, XmlValue.getCPtr(reslt));
  }

  public boolean resolveCollection(XmlTransaction txn, XmlManager mgr, String uri, XmlResults reslt) throws XmlException {
    return dbxml_javaJNI.XmlResolver_resolveCollection(swigCPtr, XmlTransaction.getCPtr(txn), XmlManager.getCPtr(mgr), uri, XmlResults.getCPtr(reslt));
  }

  public XmlInputStream resolveSchema(XmlTransaction txn, XmlManager mgr, String schemaLocation, String nameSpace) throws XmlException {
    long cPtr = dbxml_javaJNI.XmlResolver_resolveSchema(swigCPtr, XmlTransaction.getCPtr(txn), XmlManager.getCPtr(mgr), schemaLocation, nameSpace);
    return (cPtr == 0) ? null : new XmlInputStream(cPtr, true);
  }

  public XmlInputStream resolveEntity(XmlTransaction txn, XmlManager mgr, String systemId, String publicId) throws XmlException {
    long cPtr = dbxml_javaJNI.XmlResolver_resolveEntity(swigCPtr, XmlTransaction.getCPtr(txn), XmlManager.getCPtr(mgr), systemId, publicId);
    return (cPtr == 0) ? null : new XmlInputStream(cPtr, true);
  }

  public boolean resolveModuleLocation(XmlTransaction txn, XmlManager mgr, String nameSpace, XmlResults reslt) throws XmlException {
    return dbxml_javaJNI.XmlResolver_resolveModuleLocation(swigCPtr, XmlTransaction.getCPtr(txn), XmlManager.getCPtr(mgr), nameSpace, XmlResults.getCPtr(reslt));
  }

  public XmlInputStream resolveModule(XmlTransaction txn, XmlManager mgr, String moduleLocation, String nameSpace) throws XmlException {
    long cPtr = dbxml_javaJNI.XmlResolver_resolveModule(swigCPtr, XmlTransaction.getCPtr(txn), XmlManager.getCPtr(mgr), moduleLocation, nameSpace);
    return (cPtr == 0) ? null : new XmlInputStream(cPtr, true);
  }

}
