/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sleepycat.dbxml;

import com.sleepycat.db.*;
import com.sleepycat.db.internal.DbEnv;
import com.sleepycat.db.internal.DbConstants;

public class XmlStatistics {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected XmlStatistics(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XmlStatistics obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() /* no exception */ {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      dbxml_javaJNI.delete_XmlStatistics(swigCPtr);
    }
    swigCPtr = 0;
  }

  public XmlStatistics(XmlStatistics arg0) throws XmlException {
    this(dbxml_javaJNI.new_XmlStatistics(XmlStatistics.getCPtr(arg0)), true);
  }

  public double getNumberOfIndexedKeys() throws XmlException {
    return dbxml_javaJNI.XmlStatistics_getNumberOfIndexedKeys(swigCPtr);
  }

  public double getNumberOfUniqueKeys() throws XmlException {
    return dbxml_javaJNI.XmlStatistics_getNumberOfUniqueKeys(swigCPtr);
  }

  public double getSumKeyValueSize() throws XmlException {
    return dbxml_javaJNI.XmlStatistics_getSumKeyValueSize(swigCPtr);
  }

}
