

#############################################################################
# Module:           Items
# Module Desc:      XPath2 Datatypes
# Project:          Pathan, Open Source X-Path module for Xerces C++
# Project Version:  1
# tmake Template:   pathanSubdir
# Creation Date:    15:42, 2003/04/30
#############################################################################

###### Include macro definitions

MAKEDEFS = ../../../Makefile.defs
include $(MAKEDEFS)

###### Files

SOURCES     =   ATAnySimpleTypeImpl.cpp \
                ATAnyURIOrDerivedImpl.cpp \
                ATBase64BinaryOrDerivedImpl.cpp \
                ATBooleanOrDerivedImpl.cpp \
                ATDateOrDerivedImpl.cpp \
                ATDateTimeOrDerivedImpl.cpp \
                ATDecimalOrDerivedImpl.cpp \
                ATDoubleOrDerivedImpl.cpp \
                ATDurationOrDerivedImpl.cpp \
                ATFloatOrDerivedImpl.cpp \
                ATGDayOrDerivedImpl.cpp \
                ATGMonthDayOrDerivedImpl.cpp \
                ATGMonthOrDerivedImpl.cpp \
                ATGYearMonthOrDerivedImpl.cpp \
                ATGYearOrDerivedImpl.cpp \
                ATHexBinaryOrDerivedImpl.cpp \
                ATNotationOrDerivedImpl.cpp \
                ATQNameOrDerivedImpl.cpp \
                ATStringOrDerivedImpl.cpp \
                ATTimeOrDerivedImpl.cpp \
                ATUntypedAtomicImpl.cpp \
                NodeImpl.cpp 

###### Include rules

RULES = ../../../Makefile.rules
include $(RULES)
