//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSGeo.MapGuide.Viewer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSGeo.MapGuide.Viewer.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SymbolInstance&gt;
        ///              &lt;CompoundSymbolDefinition&gt;
        ///                &lt;Name&gt;BOX&lt;/Name&gt;
        ///                &lt;Description&gt;area_box.templ&lt;/Description&gt;
        ///                &lt;SimpleSymbol&gt;
        ///                  &lt;SimpleSymbolDefinition&gt;
        ///                    &lt;Name&gt;BOX&lt;/Name&gt;
        ///                    &lt;Description&gt;area_box.templ&lt;/Description&gt;
        ///                    &lt;Graphics&gt;
        ///                      &lt;Path&gt;
        ///                        &lt;Geometry&gt;M 0.25,0.0 h 0.25 M 0.25,0.25 h 0.25 M 0.0,0.5 h 0.25 M 0.0,0.75 h 0.25&lt;/Geometry&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string area_box {
            get {
                return ResourceManager.GetString("area_box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SymbolInstance&gt;
        ///              &lt;CompoundSymbolDefinition&gt;
        ///                &lt;Name&gt;CROSS&lt;/Name&gt;
        ///                &lt;Description&gt;area_cross.templ&lt;/Description&gt;
        ///                &lt;SimpleSymbol&gt;
        ///                  &lt;SimpleSymbolDefinition&gt;
        ///                    &lt;Name&gt;CROSS&lt;/Name&gt;
        ///                    &lt;Description&gt;area_cross.templ&lt;/Description&gt;
        ///                    &lt;Graphics&gt;
        ///                      &lt;Path&gt;
        ///                        &lt;Geometry&gt;M 0.0,0.0 h 0.125 M 0.25,0.25 h 0.125&lt;/Geometry&gt;
        ///                        &lt;Sca [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string area_cross {
            get {
                return ResourceManager.GetString("area_cross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SymbolInstance&gt;
        ///              &lt;SimpleSymbolDefinition&gt;
        ///                &lt;Name&gt;DASH&lt;/Name&gt;
        ///                &lt;Description&gt;area_dash.templ&lt;/Description&gt;
        ///                &lt;Graphics&gt;
        ///                  &lt;Path&gt;
        ///                    &lt;Geometry&gt;M 0.0,0.0 h 0.125 M 0.125,0.125 h 0.125&lt;/Geometry&gt;
        ///                    &lt;ScaleX&gt;%SCALEX0%&lt;/ScaleX&gt;
        ///                    &lt;ScaleY&gt;%SCALEY0%&lt;/ScaleY&gt;
        ///                    &lt;LineColor&gt;%HATCHCOLOR%&lt;/LineColor&gt;
        ///                    &lt;LineCap&gt;%LINECAP0%&lt;/LineCap&gt;
        ///                    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string area_dash {
            get {
                return ResourceManager.GetString("area_dash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SymbolInstance&gt;
        ///              &lt;CompoundSymbolDefinition&gt;
        ///                &lt;Name&gt;DOLMIT&lt;/Name&gt;
        ///                &lt;Description&gt;area_dolmit.templ&lt;/Description&gt;
        ///                &lt;SimpleSymbol&gt;
        ///                  &lt;SimpleSymbolDefinition&gt;
        ///                    &lt;Name&gt;DOLMIT&lt;/Name&gt;
        ///                    &lt;Description&gt;area_dolmit.templ&lt;/Description&gt;
        ///                    &lt;Graphics&gt;
        ///                      &lt;Path&gt;
        ///                        &lt;Geometry&gt;M 0.0,0.0 h 10.0&lt;/Geometry&gt;
        ///                        &lt;ScaleX&gt;%SCALEX0%&lt;/Sc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string area_dolmit {
            get {
                return ResourceManager.GetString("area_dolmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SymbolInstance&gt;
        ///              &lt;CompoundSymbolDefinition&gt;
        ///                &lt;Name&gt;HEX&lt;/Name&gt;
        ///                &lt;Description&gt;area_hex.templ&lt;/Description&gt;
        ///                &lt;SimpleSymbol&gt;
        ///                  &lt;SimpleSymbolDefinition&gt;
        ///                    &lt;Name&gt;HEX&lt;/Name&gt;
        ///                    &lt;Description&gt;area_hex.templ&lt;/Description&gt;
        ///                    &lt;Graphics&gt;
        ///                      &lt;Path&gt;
        ///                        &lt;Geometry&gt;M 0.0,0.0 h 0.125&lt;/Geometry&gt;
        ///                        &lt;ScaleX&gt;%SCALEX0%&lt;/ScaleX&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string area_hex {
            get {
                return ResourceManager.GetString("area_hex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SymbolInstance&gt;
        ///              &lt;SimpleSymbolDefinition&gt;
        ///                &lt;Name&gt;LINE&lt;/Name&gt;
        ///                &lt;Description&gt;area_line.templ&lt;/Description&gt;
        ///                &lt;Graphics&gt;
        ///                  &lt;Path&gt;
        ///                    &lt;Geometry&gt;M 0.0,0.0 h 10.0&lt;/Geometry&gt;
        ///                    &lt;ScaleX&gt;%SCALEX%&lt;/ScaleX&gt;
        ///                    &lt;ScaleY&gt;%SCALEY%&lt;/ScaleY&gt;
        ///                    &lt;LineColor&gt;%HATCHCOLOR%&lt;/LineColor&gt;
        ///                    &lt;LineCap&gt;%LINECAP%&lt;/LineCap&gt;
        ///                    &lt;LineJoin&gt;%LINEJOIN%&lt;/Lin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string area_line {
            get {
                return ResourceManager.GetString("area_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SymbolInstance&gt;
        ///              &lt;SimpleSymbolDefinition&gt;
        ///                &lt;Name&gt;LINE&lt;/Name&gt;
        ///                &lt;Description&gt;area_line_135.templ&lt;/Description&gt;
        ///                &lt;Graphics&gt;
        ///                  &lt;Path&gt;
        ///                    &lt;Geometry&gt;M 0.0,0.0 h 10.0&lt;/Geometry&gt;
        ///                    &lt;ScaleX&gt;%SCALEX%&lt;/ScaleX&gt;
        ///                    &lt;ScaleY&gt;%SCALEY%&lt;/ScaleY&gt;
        ///                    &lt;LineColor&gt;%HATCHCOLOR%&lt;/LineColor&gt;
        ///                    &lt;LineCap&gt;%LINECAP%&lt;/LineCap&gt;
        ///                    &lt;LineJoin&gt;%LINEJOIN%&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string area_line_135 {
            get {
                return ResourceManager.GetString("area_line_135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SymbolInstance&gt;
        ///              &lt;SimpleSymbolDefinition&gt;
        ///                &lt;Name&gt;LINE&lt;/Name&gt;
        ///                &lt;Description&gt;area_line_45.templ&lt;/Description&gt;
        ///                &lt;Graphics&gt;
        ///                  &lt;Path&gt;
        ///                    &lt;Geometry&gt;M 0.0,0.0 h 10.0&lt;/Geometry&gt;
        ///                    &lt;ScaleX&gt;%SCALEX%&lt;/ScaleX&gt;
        ///                    &lt;ScaleY&gt;%SCALEY%&lt;/ScaleY&gt;
        ///                    &lt;LineColor&gt;%HATCHCOLOR%&lt;/LineColor&gt;
        ///                    &lt;LineCap&gt;%LINECAP%&lt;/LineCap&gt;
        ///                    &lt;LineJoin&gt;%LINEJOIN%&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string area_line_45 {
            get {
                return ResourceManager.GetString("area_line_45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SymbolInstance&gt;
        ///              &lt;SimpleSymbolDefinition&gt;
        ///                &lt;Name&gt;LINE&lt;/Name&gt;
        ///                &lt;Description&gt;area_line_90.templ&lt;/Description&gt;
        ///                &lt;Graphics&gt;
        ///                  &lt;Path&gt;
        ///                    &lt;Geometry&gt;M 0.0,0.0 h 10.0&lt;/Geometry&gt;
        ///                    &lt;ScaleX&gt;%SCALEX%&lt;/ScaleX&gt;
        ///                    &lt;ScaleY&gt;%SCALEY%&lt;/ScaleY&gt;
        ///                    &lt;LineColor&gt;%HATCHCOLOR%&lt;/LineColor&gt;
        ///                    &lt;LineCap&gt;%LINECAP%&lt;/LineCap&gt;
        ///                    &lt;LineJoin&gt;%LINEJOIN%&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string area_line_90 {
            get {
                return ResourceManager.GetString("area_line_90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SymbolInstance&gt;
        ///              &lt;CompoundSymbolDefinition&gt;
        ///                &lt;Name&gt;AREA_SYMBOL_FOREGROUND&lt;/Name&gt;
        ///                &lt;Description&gt;area_net.templ&lt;/Description&gt;
        ///                &lt;SimpleSymbol&gt;
        ///                  &lt;SimpleSymbolDefinition&gt;
        ///                    &lt;Name&gt;NET&lt;/Name&gt;
        ///                    &lt;Description&gt;area_net.templ&lt;/Description&gt;
        ///                    &lt;Graphics&gt;
        ///                      &lt;Path&gt;
        ///                        &lt;Geometry&gt;M 0.0,0.0 h 10.0&lt;/Geometry&gt;
        ///                        &lt;ScaleX&gt;%SCALE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string area_net {
            get {
                return ResourceManager.GetString("area_net", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SymbolInstance&gt;
        ///              &lt;CompoundSymbolDefinition&gt;
        ///                &lt;Name&gt;SACNCR&lt;/Name&gt;
        ///                &lt;Description&gt;area_sacncr.templ&lt;/Description&gt;
        ///                &lt;SimpleSymbol&gt;
        ///                  &lt;SimpleSymbolDefinition&gt;
        ///                    &lt;Name&gt;SACNCR&lt;/Name&gt;
        ///                    &lt;Description&gt;area_sacncr.templ&lt;/Description&gt;
        ///                    &lt;Graphics&gt;
        ///                      &lt;Path&gt;
        ///                        &lt;Geometry&gt;M 0.04688,-0.04688 h 0.0&lt;/Geometry&gt;
        ///                        &lt;ScaleX&gt;%SCAL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string area_sacncr {
            get {
                return ResourceManager.GetString("area_sacncr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SymbolInstance&gt;
        ///              &lt;SimpleSymbolDefinition&gt;
        ///                &lt;Name&gt;AREA_SYMBOL_FOREGROUND&lt;/Name&gt;
        ///                &lt;Description&gt;area_solid.templ&lt;/Description&gt;
        ///                &lt;Graphics&gt;
        ///                  &lt;Path&gt;
        ///                    &lt;Geometry&gt;M 0.0,0.0 h 100.0 v 100.0 h -100.0 z&lt;/Geometry&gt;
        ///                    &lt;ScaleX&gt;%SCALEX%&lt;/ScaleX&gt;
        ///                    &lt;ScaleY&gt;%SCALEY%&lt;/ScaleY&gt;
        ///                    &lt;FillColor&gt;%FILLCOLOR%&lt;/FillColor&gt;
        ///                    &lt;LineCap&gt;%LINECAP%&lt;/LineCap&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string area_solid {
            get {
                return ResourceManager.GetString("area_solid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SymbolInstance&gt;
        ///              &lt;CompoundSymbolDefinition&gt;
        ///                &lt;Name&gt;SQUARE&lt;/Name&gt;
        ///                &lt;Description&gt;area_square.templ&lt;/Description&gt;
        ///                &lt;SimpleSymbol&gt;
        ///                  &lt;SimpleSymbolDefinition&gt;
        ///                    &lt;Name&gt;SQUARE&lt;/Name&gt;
        ///                    &lt;Description&gt;area_square.templ&lt;/Description&gt;
        ///                    &lt;Graphics&gt;
        ///                      &lt;Path&gt;
        ///                        &lt;Geometry&gt;M 0.0,0.0 h 0.125&lt;/Geometry&gt;
        ///                        &lt;ScaleX&gt;%SCALEX0%&lt;/S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string area_square {
            get {
                return ResourceManager.GetString("area_square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SymbolInstance&gt;
        ///              &lt;SimpleSymbolDefinition&gt;
        ///                &lt;Name&gt;STEEL&lt;/Name&gt;
        ///                &lt;Description&gt;area_steel.templ&lt;/Description&gt;
        ///                &lt;Graphics&gt;
        ///                  &lt;Path&gt;
        ///                    &lt;Geometry&gt;M 0.0,0.0 h 10.0 M 0.04419,0.04419 h 10.0&lt;/Geometry&gt;
        ///                    &lt;ScaleX&gt;%SCALEX%&lt;/ScaleX&gt;
        ///                    &lt;ScaleY&gt;%SCALEY%&lt;/ScaleY&gt;
        ///                    &lt;LineColor&gt;%HATCHCOLOR%&lt;/LineColor&gt;
        ///                    &lt;LineCap&gt;%LINECAP%&lt;/LineCap&gt;
        ///                   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string area_steel {
            get {
                return ResourceManager.GetString("area_steel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to finish.
        /// </summary>
        internal static string CircleDigitizationPrompt {
            get {
                return ResourceManager.GetString("CircleDigitizationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected redline objects?.
        /// </summary>
        internal static string ConfirmDeleteRedlines {
            get {
                return ResourceManager.GetString("ConfirmDeleteRedlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} features in layer.
        /// </summary>
        internal static string CountFormat {
            get {
                return ResourceManager.GetString("CountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} other styles.
        /// </summary>
        internal static string CountOtherStyles {
            get {
                return ResourceManager.GetString("CountOtherStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} results.
        /// </summary>
        internal static string CountResults {
            get {
                return ResourceManager.GetString("CountResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {1}{0}Feature Source: {2}{0}Feature Class: {3}.
        /// </summary>
        internal static string DefaultLayerTooltip {
            get {
                return ResourceManager.GetString("DefaultLayerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {1}{0}Feature Source: {2}.
        /// </summary>
        internal static string DrawingLayerTooltip {
            get {
                return ResourceManager.GetString("DrawingLayerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A component with ID ({0}) already exists.
        /// </summary>
        internal static string ErrorComponentAlreadyExists {
            get {
                return ResourceManager.GetString("ErrorComponentAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component ({0}) does not exist.
        /// </summary>
        internal static string ErrorComponentNotFound {
            get {
                return ResourceManager.GetString("ErrorComponentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified component&apos;s target is not the Task Pane.
        /// </summary>
        internal static string ErrorComponentTargetNotTaskPane {
            get {
                return ResourceManager.GetString("ErrorComponentTargetNotTaskPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndInit: No Task Pane assigned.
        /// </summary>
        internal static string ErrorEndInitNoTaskPaneAssigned {
            get {
                return ResourceManager.GetString("ErrorEndInitNoTaskPaneAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the geometry property: {0}.
        /// </summary>
        internal static string ErrorGeometryPropertyNotFound {
            get {
                return ResourceManager.GetString("ErrorGeometryPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} is not a valid component property as it has not been marked with the MgComponentProperty attribute.
        /// </summary>
        internal static string ErrorInvalidComponentProperty {
            get {
                return ResourceManager.GetString("ErrorInvalidComponentProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid map name &quot;{0}&quot;. A map name cannot have spaces or any of the following characters: \:*?&quot;&lt;&gt;|&amp;&apos;%=/.
        /// </summary>
        internal static string ErrorInvalidMapName {
            get {
                return ResourceManager.GetString("ErrorInvalidMapName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid search layer. Layer {0} not found on map.
        /// </summary>
        internal static string ErrorInvalidSearchLayer {
            get {
                return ResourceManager.GetString("ErrorInvalidSearchLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer metadata not fully initialized.
        /// </summary>
        internal static string ErrorLayerMetadataNotFullyInitialized {
            get {
                return ResourceManager.GetString("ErrorLayerMetadataNotFullyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed enum string. Expected enum:className:value.
        /// </summary>
        internal static string ErrorMalformedEnumString {
            get {
                return ResourceManager.GetString("ErrorMalformedEnumString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A map named ({0}) was not found in the AppLayout.
        /// </summary>
        internal static string ErrorMapNotFound {
            get {
                return ResourceManager.GetString("ErrorMapNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is not yet implemented.
        /// </summary>
        internal static string ErrorNotImplemented {
            get {
                return ResourceManager.GetString("ErrorNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search filter is missing the required $USER_VARIABLE placeholder.
        /// </summary>
        internal static string ErrorSearchFilterMissingPlaceholder {
            get {
                return ResourceManager.GetString("ErrorSearchFilterMissingPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream is not rewindable.
        /// </summary>
        internal static string ErrorStreamNotRewindable {
            get {
                return ResourceManager.GetString("ErrorStreamNotRewindable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target: No Task Pane assigned.
        /// </summary>
        internal static string ErrorTargetNoTaskPaneAssigned {
            get {
                return ResourceManager.GetString("ErrorTargetNoTaskPaneAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported item type: {0}.
        /// </summary>
        internal static string ErrorUnsupportedItemType {
            get {
                return ResourceManager.GetString("ErrorUnsupportedItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewer not initialized via Init().
        /// </summary>
        internal static string ErrorViewerNotInitialized {
            get {
                return ResourceManager.GetString("ErrorViewerNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press ESC to cancel.
        /// </summary>
        internal static string GeneralDigitizationInstructions {
            get {
                return ResourceManager.GetString("GeneralDigitizationInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinity.
        /// </summary>
        internal static string Infinity {
            get {
                return ResourceManager.GetString("Infinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SimpleSymbolDefinition&gt;
        ///                &lt;Name&gt;LINE_SYMBOL&lt;/Name&gt;
        ///                &lt;Description&gt;line_border.templ&lt;/Description&gt;
        ///                &lt;Graphics&gt;
        ///                  &lt;Path&gt;
        ///                    &lt;Geometry&gt;M 0,0 L 5,0 M 7.5,0 L 12.5,0 M 15,0 L 15,0 &lt;/Geometry&gt;
        ///                    &lt;ScaleX&gt;%SCALEX%&lt;/ScaleX&gt;
        ///                    &lt;ScaleY&gt;%SCALEY%&lt;/ScaleY&gt;
        ///                    &lt;LineColor&gt;%LINECOLOR%&lt;/LineColor&gt;
        ///                    &lt;LineWeight&gt;%LINEWEIGHT%&lt;/LineWeight&gt;
        ///                    &lt;LineWeightSc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string line_border {
            get {
                return ResourceManager.GetString("line_border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SimpleSymbolDefinition&gt;
        ///                &lt;Name&gt;LINE_SYMBOL&lt;/Name&gt;
        ///                &lt;Description&gt;line_dash.templ&lt;/Description&gt;
        ///                &lt;Graphics&gt;
        ///                  &lt;Path&gt;
        ///                    &lt;Geometry&gt;M 0,0 L 6,0&lt;/Geometry&gt;
        ///                    &lt;ScaleX&gt;%SCALEX%&lt;/ScaleX&gt;
        ///                    &lt;ScaleY&gt;%SCALEY%&lt;/ScaleY&gt;
        ///                    &lt;LineColor&gt;%LINECOLOR%&lt;/LineColor&gt;
        ///                    &lt;LineWeight&gt;%LINEWEIGHT%&lt;/LineWeight&gt;
        ///                    &lt;LineWeightScalable&gt;false&lt;/LineWeightScalable&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string line_dash {
            get {
                return ResourceManager.GetString("line_dash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SimpleSymbolDefinition&gt;
        ///                &lt;Name&gt;LINE_SYMBOL&lt;/Name&gt;
        ///                &lt;Description&gt;line_dashdot.templ&lt;/Description&gt;
        ///                &lt;Graphics&gt;
        ///                  &lt;Path&gt;
        ///                    &lt;Geometry&gt;M 0,0 L 5,0 M 7.5,0 L 7.5,0 &lt;/Geometry&gt;
        ///                    &lt;ScaleX&gt;%SCALEX%&lt;/ScaleX&gt;
        ///                    &lt;ScaleY&gt;%SCALEY%&lt;/ScaleY&gt;
        ///                    &lt;LineColor&gt;%LINECOLOR%&lt;/LineColor&gt;
        ///                    &lt;LineWeight&gt;%LINEWEIGHT%&lt;/LineWeight&gt;
        ///                    &lt;LineWeightScalable&gt;false&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string line_dashdot {
            get {
                return ResourceManager.GetString("line_dashdot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SimpleSymbolDefinition&gt;
        ///                &lt;Name&gt;LINE_SYMBOL&lt;/Name&gt;
        ///                &lt;Description&gt;line_dashdotdot.templ&lt;/Description&gt;
        ///                &lt;Graphics&gt;
        ///                  &lt;Path&gt;
        ///                    &lt;Geometry&gt;M 0,0 L 40,0 M 80,0 L 120,0 M 160,0 L 200,0 M 240,0 L 320,0 &lt;/Geometry&gt;
        ///                    &lt;ScaleX&gt;%SCALEX%&lt;/ScaleX&gt;
        ///                    &lt;ScaleY&gt;%SCALEY%&lt;/ScaleY&gt;
        ///                    &lt;LineColor&gt;%LINECOLOR%&lt;/LineColor&gt;
        ///                    &lt;LineWeight&gt;%LINEWEIGHT%&lt;/LineWeight&gt;
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string line_dashdotdot {
            get {
                return ResourceManager.GetString("line_dashdotdot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SimpleSymbolDefinition&gt;
        ///                &lt;Name&gt;LINE_SYMBOL&lt;/Name&gt;
        ///                &lt;Description&gt;line_divide.templ&lt;/Description&gt;
        ///                &lt;Graphics&gt;
        ///                  &lt;Path&gt;
        ///                    &lt;Geometry&gt;M 0,0 L 5,0 M 7.5,0 L 7.5,0 M 10,0 L 10,0 &lt;/Geometry&gt;
        ///                    &lt;ScaleX&gt;%SCALEX%&lt;/ScaleX&gt;
        ///                    &lt;ScaleY&gt;%SCALEY%&lt;/ScaleY&gt;
        ///                    &lt;LineColor&gt;%LINECOLOR%&lt;/LineColor&gt;
        ///                    &lt;LineWeight&gt;%LINEWEIGHT%&lt;/LineWeight&gt;
        ///                    &lt;LineWeightSca [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string line_divide {
            get {
                return ResourceManager.GetString("line_divide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SimpleSymbolDefinition&gt;
        ///                &lt;Name&gt;LINE_SYMBOL&lt;/Name&gt;
        ///                &lt;Description&gt;line_dot.templ&lt;/Description&gt;
        ///                &lt;Graphics&gt;
        ///                  &lt;Path&gt;
        ///                    &lt;Geometry&gt;M 0,0 L 0,0 &lt;/Geometry&gt;
        ///                    &lt;ScaleX&gt;%SCALEX%&lt;/ScaleX&gt;
        ///                    &lt;ScaleY&gt;%SCALEY%&lt;/ScaleY&gt;
        ///                    &lt;LineColor&gt;%LINECOLOR%&lt;/LineColor&gt;
        ///                    &lt;LineWeight&gt;%LINEWEIGHT%&lt;/LineWeight&gt;
        ///                    &lt;LineWeightScalable&gt;false&lt;/LineWeightScalable&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string line_dot {
            get {
                return ResourceManager.GetString("line_dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SimpleSymbolDefinition&gt;
        ///                &lt;Name&gt;LINE_SYMBOL&lt;/Name&gt;
        ///                &lt;Description&gt;line_fenceline1.templ&lt;/Description&gt;
        ///                &lt;Graphics&gt;
        ///                  &lt;Path&gt;
        ///                    &lt;Geometry&gt;M 2.5,0 A 1,1 0 0 0 4.5,-3.67394039744206e-016 M 4.5,-3.67394039744206e-016 A 1,1 0 0 0 2.5,2.44929359829471e-016 &lt;/Geometry&gt;
        ///                    &lt;ScaleX&gt;%SCALEX0%&lt;/ScaleX&gt;
        ///                    &lt;ScaleY&gt;%SCALEY0%&lt;/ScaleY&gt;
        ///                    &lt;LineColor&gt;%LINECOLOR%&lt;/LineColor&gt;
        ///                [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string line_fenceline1 {
            get {
                return ResourceManager.GetString("line_fenceline1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SimpleSymbolDefinition&gt;
        ///                &lt;Name&gt;LINE_SYMBOL&lt;/Name&gt;
        ///                &lt;Description&gt;line_rail.templ&lt;/Description&gt;
        ///                &lt;Graphics&gt;
        ///                  &lt;Path&gt;
        ///                    &lt;Geometry&gt;M 2.0,0 l 0,2.5 M 2.0,0 l 0,-2.5 &lt;/Geometry&gt;
        ///                    &lt;ScaleX&gt;%SCALEX0%&lt;/ScaleX&gt;
        ///                    &lt;ScaleY&gt;%SCALEY0%&lt;/ScaleY&gt;
        ///                    &lt;LineColor&gt;%LINECOLOR%&lt;/LineColor&gt;
        ///                    &lt;LineWeight&gt;%LINEWEIGHT%&lt;/LineWeight&gt;
        ///                    &lt;LineWeightScalable&gt;fal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string line_rail {
            get {
                return ResourceManager.GetString("line_rail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SimpleSymbolDefinition&gt;
        ///                &lt;Name&gt;LINE_SYMBOL&lt;/Name&gt;
        ///                &lt;Description&gt;line_solid.templ&lt;/Description&gt;
        ///                &lt;Graphics&gt;
        ///                  &lt;Path&gt;
        ///                    &lt;Geometry&gt;M 0.0,0.0 h 4.0&lt;/Geometry&gt;
        ///                    &lt;ScaleX&gt;%SCALEX%&lt;/ScaleX&gt;
        ///                    &lt;ScaleY&gt;%SCALEY%&lt;/ScaleY&gt;
        ///                    &lt;LineColor&gt;%LINECOLOR%&lt;/LineColor&gt;
        ///                    &lt;LineWeight&gt;%LINEWEIGHT%&lt;/LineWeight&gt;
        ///                    &lt;LineWeightScalable&gt;false&lt;/LineWeightScala [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string line_solid {
            get {
                return ResourceManager.GetString("line_solid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to finish.
        /// </summary>
        internal static string LineDigitizationPrompt {
            get {
                return ResourceManager.GetString("LineDigitizationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click again to add a new vertex.\nDouble-click to finish.
        /// </summary>
        internal static string LineStringDigitizationPrompt {
            get {
                return ResourceManager.GetString("LineStringDigitizationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;FeatureSource xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xsi:noNamespaceSchemaLocation=&quot;FeatureSource-1.0.0.xsd&quot;&gt;
        ///  &lt;Provider&gt;%s&lt;/Provider&gt;
        ///  &lt;Parameter&gt;
        ///    &lt;Name&gt;%s&lt;/Name&gt;
        ///    &lt;Value&gt;%%MG_DATA_FILE_PATH%%%s&lt;/Value&gt;
        ///  &lt;/Parameter&gt;
        ///  %s
        ///&lt;/FeatureSource&gt;.
        /// </summary>
        internal static string markupfeaturesource {
            get {
                return ResourceManager.GetString("markupfeaturesource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///&lt;LayerDefinition xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xsi:noNamespaceSchemaLocation=&quot;LayerDefinition-1.0.0.xsd&quot; version=&quot;1.0.0&quot;&gt;
        ///  &lt;VectorLayerDefinition&gt;
        ///    &lt;ResourceId&gt;%s&lt;/ResourceId&gt;
        ///    &lt;FeatureName&gt;%s&lt;/FeatureName&gt;
        ///    &lt;FeatureNameType&gt;FeatureClass&lt;/FeatureNameType&gt;
        ///    &lt;PropertyMapping&gt;
        ///      &lt;Name&gt;Text&lt;/Name&gt;
        ///      &lt;Value&gt;Text&lt;/Value&gt;
        ///    &lt;/PropertyMapping&gt;
        ///    &lt;Geometry&gt;Geometry&lt;/Geometr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string markuplayerdefinition {
            get {
                return ResourceManager.GetString("markuplayerdefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;LayerDefinition xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; version=&quot;2.4.0&quot; xsi:noNamespaceSchemaLocation=&quot;LayerDefinition-2.4.0.xsd&quot;&gt;
        ///  &lt;VectorLayerDefinition&gt;
        ///    &lt;ResourceId&gt;#{RESOURCE_ID}&lt;/ResourceId&gt;
        ///    &lt;FeatureName&gt;#{FEATURE_CLASS}&lt;/FeatureName&gt;
        ///    &lt;FeatureNameType&gt;FeatureClass&lt;/FeatureNameType&gt;
        ///    &lt;PropertyMapping&gt;
        ///      &lt;Name&gt;Text&lt;/Name&gt;
        ///      &lt;Value&gt;Text&lt;/Value&gt;
        ///    &lt;/PropertyMapping&gt;
        ///    &lt;Geometry&gt;Geometry&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string markuplayerdefinition_advanced {
            get {
                return ResourceManager.GetString("markuplayerdefinition_advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string MenuTools {
            get {
                return ResourceManager.GetString("MenuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer Layer ({0}) created.
        /// </summary>
        internal static string MsgBufferLayerCreated {
            get {
                return ResourceManager.GetString("MsgBufferLayerCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer Layer ({0}) updated.
        /// </summary>
        internal static string MsgBufferLayerUpdated {
            get {
                return ResourceManager.GetString("MsgBufferLayerUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for this layer.
        /// </summary>
        internal static string MsgEnterNameForLayer {
            get {
                return ResourceManager.GetString("MsgEnterNameForLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include one or more layers to create a buffer from.
        /// </summary>
        internal static string MsgIncludeLayersToBuffer {
            get {
                return ResourceManager.GetString("MsgIncludeLayersToBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Layer ({0}) created.
        /// </summary>
        internal static string MsgThemeLayerCreated {
            get {
                return ResourceManager.GetString("MsgThemeLayerCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Ctrl-Z to undo last point.\nPress ESC to cancel.
        /// </summary>
        internal static string MultiSegmentDigitzationInstructions {
            get {
                return ResourceManager.GetString("MultiSegmentDigitzationInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to finish.
        /// </summary>
        internal static string PointDigitizationPrompt {
            get {
                return ResourceManager.GetString("PointDigitizationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click again to add a new vertex.\nDouble-click to finish.
        /// </summary>
        internal static string PolygonDigitizationPrompt {
            get {
                return ResourceManager.GetString("PolygonDigitizationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to finish.
        /// </summary>
        internal static string RectangleDigitizationPrompt {
            get {
                return ResourceManager.GetString("RectangleDigitizationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redline Layers.
        /// </summary>
        internal static string RedlineLayerGroupLabel {
            get {
                return ResourceManager.GetString("RedlineLayerGroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Language.
        /// </summary>
        internal static string SetLanguage {
            get {
                return ResourceManager.GetString("SetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHP only allows a single geometry type.
        /// </summary>
        internal static string SHPGeometryLimitation {
            get {
                return ResourceManager.GetString("SHPGeometryLimitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the text for the selected redline(s).
        /// </summary>
        internal static string SpecifyRedlineText {
            get {
                return ResourceManager.GetString("SpecifyRedlineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} features selected.
        /// </summary>
        internal static string StatFeaturesSelected {
            get {
                return ResourceManager.GetString("StatFeaturesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [unsupported data type].
        /// </summary>
        internal static string StrUnsupportedDataType {
            get {
                return ResourceManager.GetString("StrUnsupportedDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Selection.
        /// </summary>
        internal static string TextClearSelection {
            get {
                return ResourceManager.GetString("TextClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy map to clipboard.
        /// </summary>
        internal static string TextCopyMap {
            get {
                return ResourceManager.GetString("TextCopyMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digitize Circle.
        /// </summary>
        internal static string TextDigitizeCircle {
            get {
                return ResourceManager.GetString("TextDigitizeCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digitize Line.
        /// </summary>
        internal static string TextDigitizeLine {
            get {
                return ResourceManager.GetString("TextDigitizeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digitize Line String.
        /// </summary>
        internal static string TextDigitizeLineString {
            get {
                return ResourceManager.GetString("TextDigitizeLineString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digitize Point.
        /// </summary>
        internal static string TextDigitizePoint {
            get {
                return ResourceManager.GetString("TextDigitizePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digitize Polygon.
        /// </summary>
        internal static string TextDigitizePolygon {
            get {
                return ResourceManager.GetString("TextDigitizePolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digitize Rectangle.
        /// </summary>
        internal static string TextDigitizeRectangle {
            get {
                return ResourceManager.GetString("TextDigitizeRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Tooltips.
        /// </summary>
        internal static string TextDisableTooltips {
            get {
                return ResourceManager.GetString("TextDisableTooltips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Tooltips.
        /// </summary>
        internal static string TextEnableTooltips {
            get {
                return ResourceManager.GetString("TextEnableTooltips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Search Criteria.
        /// </summary>
        internal static string TextEnterSearchCriteria {
            get {
                return ResourceManager.GetString("TextEnterSearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string TextExitApplication {
            get {
                return ResourceManager.GetString("TextExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        internal static string TextLayers {
            get {
                return ResourceManager.GetString("TextLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers (Refreshing...).
        /// </summary>
        internal static string TextLayersRefreshing {
            get {
                return ResourceManager.GetString("TextLayersRefreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Package.
        /// </summary>
        internal static string TextLoadPackage {
            get {
                return ResourceManager.GetString("TextLoadPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing is selected.
        /// </summary>
        internal static string TextNoSelection {
            get {
                return ResourceManager.GetString("TextNoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options Saved.
        /// </summary>
        internal static string TextOptionsSaved {
            get {
                return ResourceManager.GetString("TextOptionsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Loaded.
        /// </summary>
        internal static string TextPackageLoaded {
            get {
                return ResourceManager.GetString("TextPackageLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan.
        /// </summary>
        internal static string TextPan {
            get {
                return ResourceManager.GetString("TextPan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot to DWF.
        /// </summary>
        internal static string TextPlotToDwf {
            get {
                return ResourceManager.GetString("TextPlotToDwf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string TextPrint {
            get {
                return ResourceManager.GetString("TextPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Map.
        /// </summary>
        internal static string TextRefreshMap {
            get {
                return ResourceManager.GetString("TextRefreshMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string TextScale {
            get {
                return ResourceManager.GetString("TextScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string TextSelect {
            get {
                return ResourceManager.GetString("TextSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Polygon.
        /// </summary>
        internal static string TextSelectPolygon {
            get {
                return ResourceManager.GetString("TextSelectPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Radius.
        /// </summary>
        internal static string TextSelectRadius {
            get {
                return ResourceManager.GetString("TextSelectRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Pane.
        /// </summary>
        internal static string TextTaskPane {
            get {
                return ResourceManager.GetString("TextTaskPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewer Options.
        /// </summary>
        internal static string TextViewerOptions {
            get {
                return ResourceManager.GetString("TextViewerOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Extents.
        /// </summary>
        internal static string TextZoomExtents {
            get {
                return ResourceManager.GetString("TextZoomExtents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        internal static string TextZoomIn {
            get {
                return ResourceManager.GetString("TextZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Next.
        /// </summary>
        internal static string TextZoomNext {
            get {
                return ResourceManager.GetString("TextZoomNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        internal static string TextZoomOut {
            get {
                return ResourceManager.GetString("TextZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Previous.
        /// </summary>
        internal static string TextZoomPrevious {
            get {
                return ResourceManager.GetString("TextZoomPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to Selection.
        /// </summary>
        internal static string TextZoomToSelection {
            get {
                return ResourceManager.GetString("TextZoomToSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {1}{0}Feature Source: {2}{0}Feature Class: {3}{0}Number of Rules: {4}.
        /// </summary>
        internal static string ThemedLayerTooltip {
            get {
                return ResourceManager.GetString("ThemedLayerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal.
        /// </summary>
        internal static string ThemeEqual {
            get {
                return ResourceManager.GetString("ThemeEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual.
        /// </summary>
        internal static string ThemeIndividual {
            get {
                return ResourceManager.GetString("ThemeIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jenks (Natural Breaks).
        /// </summary>
        internal static string ThemeJenks {
            get {
                return ResourceManager.GetString("ThemeJenks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantile.
        /// </summary>
        internal static string ThemeQuantile {
            get {
                return ResourceManager.GetString("ThemeQuantile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Deviation.
        /// </summary>
        internal static string ThemeStandardDeviation {
            get {
                return ResourceManager.GetString("ThemeStandardDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer.
        /// </summary>
        internal static string TitleBuffer {
            get {
                return ResourceManager.GetString("TitleBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Redlines.
        /// </summary>
        internal static string TitleDeleteRedlines {
            get {
                return ResourceManager.GetString("TitleDeleteRedlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Redline Text.
        /// </summary>
        internal static string TitleEditRedlineText {
            get {
                return ResourceManager.GetString("TitleEditRedlineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure.
        /// </summary>
        internal static string TitleMeasure {
            get {
                return ResourceManager.GetString("TitleMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Settings.
        /// </summary>
        internal static string TitlePrintSettings {
            get {
                return ResourceManager.GetString("TitlePrintSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string TitleQuery {
            get {
                return ResourceManager.GetString("TitleQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redline.
        /// </summary>
        internal static string TitleRedline {
            get {
                return ResourceManager.GetString("TitleRedline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string TitleSearch {
            get {
                return ResourceManager.GetString("TitleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the Task Pane.
        /// </summary>
        internal static string TitleTaskPaneAbout {
            get {
                return ResourceManager.GetString("TitleTaskPaneAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string TitleTheme {
            get {
                return ResourceManager.GetString("TitleTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewer Options.
        /// </summary>
        internal static string TitleViewerOptions {
            get {
                return ResourceManager.GetString("TitleViewerOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltips are enabled. Click to disable.
        /// </summary>
        internal static string TooltipDisableTooltips {
            get {
                return ResourceManager.GetString("TooltipDisableTooltips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltips are disabled. Click to enable.
        /// </summary>
        internal static string TooltipEnableTooltips {
            get {
                return ResourceManager.GetString("TooltipEnableTooltips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: The specified initial task component id ({0}) does not exist in the AppLayout.
        /// </summary>
        internal static string WarnInitialTaskComponentNotFound {
            get {
                return ResourceManager.GetString("WarnInitialTaskComponentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Attempted to invoke the component with ID ({0}), but could not find any component with this ID.
        /// </summary>
        internal static string WarnInvokeNonExistentComponent {
            get {
                return ResourceManager.GetString("WarnInvokeNonExistentComponent", resourceCulture);
            }
        }
    }
}
