# $Id: Makefile,v 1.2 2006/06/13 19:32:55 gmf Exp $

###### Include macro definitions

MAKEDEFS = $(builddir)/Makefile.defs
include $(MAKEDEFS)

###### Files

SOURCES= $(DBXML_NODESTORE_SOURCES)

###### Include rules

RULES = $(builddir)/Makefile.rules
include $(RULES)
