# $Id: Makefile,v 1.1 2004/08/20 12:20:08 awood Exp $

###### Include macro definitions

MAKEDEFS = ../../../build_unix/Makefile.defs
include $(MAKEDEFS)

###### Files

SOURCES= $(UNIT_TEST_DATABASE_SOURCES)

###### Include rules

RULES = ../../../build_unix/Makefile.rules
include $(RULES)

