//
//  Copyright (C) 2004-2006  Autodesk, Inc.
//
//  This library is free software; you can redistribute it and/or
//  modify it under the terms of version 2.1 of the GNU Lesser
//  General Public License as published by the Free Software Foundation.
//
//  This library is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
//  Lesser General Public License for more details.
//
//  You should have received a copy of the GNU Lesser General Public
//  License along with this library; if not, write to the Free Software
//  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
//

#include "BaseServiceDefs.cpp"
#include "ClassDefinition.cpp"
#include "Command.cpp"
#include "ConnectionProperties.cpp"
#include "CreateSdfParams.cpp"
#include "CustomLogoInfo.cpp"
#include "CustomTextInfo.cpp"
#include "DataPropertyDefinition.cpp"
#include "DataReader.cpp"
#include "DeleteFeatures.cpp"
#include "DrawingDefs.cpp"
#include "DrawingService.cpp"
#include "DwfVersion.cpp"
#include "FeatureAggregateOptions.cpp"
#include "FeatureCommandCollection.cpp"
#include "FeatureDefs.cpp"
#include "FeatureInformation.cpp"
#include "FeatureProperty.cpp"
#include "FeatureQueryOptions.cpp"
#include "FeatureReader.cpp"
#include "FeatureService.cpp"
#include "FeatureSet.cpp"
#include "FeatureSourceParams.cpp"
#include "GeometricPropertyDefinition.cpp"
#include "GeometryProperty.cpp"
#include "ImageFormats.cpp"
#include "InsertFeatures.cpp"
#include "Layout.cpp"
#include "LongTransactionData.cpp"
#include "LongTransactionReader.cpp"
#include "MappingDefs.cpp"
#include "MappingService.cpp"
#include "MapPlot.cpp"
#include "MapPlotCollection.cpp"
#include "PlotSpecification.cpp"
#include "PrintLayout.cpp"
#include "ProxyDataReader.cpp"
#include "ProxyDrawingService.cpp"
#include "ProxyFeatureReader.cpp"
#include "ProxyFeatureService.cpp"
#include "ProxyMappingService.cpp"
#include "ProxyRenderingService.cpp"
#include "ProxyResourceService.cpp"
#include "ProxySqlDataReader.cpp"
#include "ProxyTileService.cpp"
#include "Raster.cpp"
#include "RasterProperty.cpp"
#include "RasterPropertyDefinition.cpp"
#include "RasterTypes.cpp"
#include "RenderingDefs.cpp"
#include "RenderingService.cpp"
#include "Resource.cpp"
#include "ResourceDefs.cpp"
#include "ResourceIdentifier.cpp"
#include "ResourceService.cpp"
#include "ServerAdmin.cpp"
#include "ServerAdminDefs.cpp"
#include "ServerConnection.cpp"
#include "ServerConnectionImp.cpp"
#include "ServerConnectionPool.cpp"
#include "ServerConnectionStack.cpp"
#include "ServerInformation.cpp"
#include "Service.cpp"
#include "ServiceFactory.cpp"
#include "Site.cpp"
#include "SiteConnection.cpp"
#include "SpatialContextData.cpp"
#include "SpatialContextReader.cpp"
#include "SqlDataReader.cpp"
#include "TileDefs.cpp"
#include "TileService.cpp"
#include "UpdateFeatures.cpp"
#include "FeatureSchema.cpp"
#include "FeatureSchemaCollection.cpp"
#include "ClassDefinitionCollection.cpp"
#include "UnitType.cpp"
#include "ObjectPropertyDefinition.cpp"
#include "ProxyGwsFeatureReader.cpp"
