

#############################################################################
# Module:           factory
# Module Desc:      Factories
# Project:          Pathan, Open Source X-Path module for Xerces C++
# Project Version:  1
# tmake Template:   pathanSubdir
# Creation Date:    14:44, 2001/09/28
#############################################################################

###### Include macro definitions

MAKEDEFS = ../../Makefile.defs
include $(MAKEDEFS)

###### Files

SOURCES     = DatatypeFactory.cpp \
    FuncFactory.cpp \
    PathanFactoryImpl.cpp

###### Include rules

RULES = ../../Makefile.rules
include $(RULES)
