# $Id: Makefile,v 1.2 2004/08/19 16:52:17 gareth Exp $

###### Include macro definitions

MAKEDEFS = ../../../build_unix/Makefile.defs
include $(MAKEDEFS)

###### Files

SOURCES= $(EXAMPLE_SOURCES)

###### Include rules

RULES = ../../../build_unix/Makefile.rules
include $(RULES)

