# $Id: Makefile,v 1.4 2006/07/11 21:08:59 gmf Exp $

###### Include macro definitions

MAKEDEFS = $(builddir)/Makefile.defs
include $(MAKEDEFS)

###### Files

SOURCES= $(EXAMPLE_GSG_SOURCES)

###### Include rules

RULES = $(builddir)/Makefile.rules
include $(RULES)

