# $Id: Makefile,v 1.4 2006/06/13 19:33:26 gmf Exp $

###### Include macro definitions

MAKEDEFS = $(builddir)/Makefile.defs
include $(MAKEDEFS)

###### Files

SOURCES= $(SHELL_SOURCES)

###### Include rules

RULES = $(builddir)/Makefile.rules
include $(RULES)



