# $Id: Makefile,v 1.1 2004/08/21 17:21:40 gmf Exp $

###### Include macro definitions

MAKEDEFS = ../../../build_unix/Makefile.defs
include $(MAKEDEFS)

###### Files

SOURCES= $(DBXML_NODESTORE_SOURCES)

###### Include rules

RULES = ../../../build_unix/Makefile.rules
include $(RULES)
