
// -*- C++ -*-
// $Id: Version.h 90979 2010-07-04 16:59:11Z johnnyw $
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.

#define ACE_MAJOR_VERSION 5
#define ACE_MINOR_VERSION 8
#define ACE_BETA_VERSION 0
#define ACE_VERSION "5.8"
