

#############################################################################
# Module:           Navigation
# Module Desc:      Navigating the tree
# Project:          Pathan, Open Source X-Path module for Xerces C++
# Project Version:  1
# tmake Template:   pathanSubdir
# Creation Date:    14:44, 2001/09/28
#############################################################################

###### Include macro definitions

MAKEDEFS = ../../Makefile.defs
include $(MAKEDEFS)

###### Files

SOURCES     = \
		AncestorAxis.cpp \
		AncestorOrSelfAxis.cpp \
		ChildAxis.cpp \
		DescendantAxis.cpp \
		DescendantOrSelfAxis.cpp \
		FollowingAxis.cpp \
		FollowingSiblingAxis.cpp \
		ParentAxis.cpp \
		PrecedingAxis.cpp \
		PrecedingSiblingAxis.cpp \
		SelfAxis.cpp \
		NodeTest.cpp \
		Axis.cpp \
		AttributeAxis.cpp \
		NamespaceAxis.cpp

###### Include rules

RULES = ../../Makefile.rules
include $(RULES)
