#!/bin/sh -
#	$Id: s_win32_vcproj,v 1.2 2006/09/19 16:41:56 gmfeinberg Exp $
#
# Build Windows .vcproj files for Visual Studio 7.1, which can
# be upgraded to Visual Studio 8 (2005) format by VS itself

BUILDDIR=../Win32Projects/VC7.1
OUTDIR=../../build/windows/VC7.1
TEMPLATEDIR=.
SRCFILES=srcfiles.in
# for now, do not parameterize the filter templates
FILT_START="filter_vcproj.start"
FILT_END="filter_vcproj.end"
# intput templates
LIB_SRC=$TEMPLATEDIR/xqilla_vcproj.src
DLL_SRC=$TEMPLATEDIR/dll_vcproj.src
APP_SRC=$TEMPLATEDIR/app_vcproj.src
TEST_SRC=$TEMPLATEDIR/test_vcproj.src
FILT_FILE_SRC=$TEMPLATEDIR/srcfile_filt_vcproj.src
FILE_SRC=$TEMPLATEDIR/srcfile_vcproj.src
EXT=vcproj

# source dependencies
. s_win32_common

generate_projects

# don't do solution yet
exit 0

# generate XQilla.sln from template
sed -f lib_paths.sed < $TEMPLATEDIR/XQilla.sln.template > $BUILDDIR/XQilla.sln.new
cmp $BUILDDIR/XQilla.sln.new $BUILDDIR/XQilla.sln > /dev/null 2>&1 ||
	(echo "Building XQilla.sln" && rm -f $BUILDDIR/XQilla.sln &&
	    cp $BUILDDIR/XQilla.sln.new $BUILDDIR/XQilla.sln && chmod 664 $BUILDDIR/XQilla.sln)
#rm -f $BUILDDIR/XQilla.sln.new

rm -f $TMPA
