# $Id: Makefile,v 1.1 2006/07/11 21:08:56 gmf Exp $

###### Include macro definitions

MAKEDEFS = $(builddir)/Makefile.defs
include $(MAKEDEFS)

###### Files

SOURCES= $(EXAMPLE_BASIC_SOURCES)

###### Include rules

RULES = $(builddir)/Makefile.rules
include $(RULES)

