

#############################################################################
# Module:           Collations
# Module Desc:      Collations Module
# Project:          Pathan, Open Source X-Path module for Xerces C++
# Project Version:  1
# tmake Template:   pathanSubdir
# Creation Date:    14:44, 2001/09/28
#############################################################################

###### Include macro definitions

MAKEDEFS = ../../Makefile.defs
include $(MAKEDEFS)

###### Files

SOURCES   = CollationImpl.cpp \
			UCANormalizer.cpp \
			UCANormalizer1.cpp \
			UCANormalizer2.cpp \
			CodepointCollation.cpp

###### Include rules

RULES = ../../Makefile.rules
include $(RULES)
