# $Id: Makefile,v 1.3 2006/06/13 19:33:22 gmf Exp $

###### Include macro definitions

MAKEDEFS = $(builddir)/Makefile.defs
include $(MAKEDEFS)

###### Files

SOURCES= $(LOAD_CONTAINER_SOURCES)

###### Include rules

RULES = $(builddir)/Makefile.rules
include $(RULES)

