# $Id: Makefile,v 1.1 2004/09/01 16:47:46 awood Exp $

###### Include macro definitions

MAKEDEFS = ../../../build_unix/Makefile.defs
include $(MAKEDEFS)

###### Files

SOURCES= $(UNIT_TEST_SOURCES)

###### Include rules

RULES = ../../../build_unix/Makefile.rules
include $(RULES)

