#
# Makefile.bor,v 1.2 2003/12/21 10:14:16 jwillemsen Exp
#

NAME = main
OBJFILES = \
	$(OBJDIR)\main.obj \
	$(OBJDIR)\HTTP_10.obj \
	$(OBJDIR)\HTTP_10_Request.obj \
	$(OBJDIR)\HTTP_10_Read.obj \
	$(OBJDIR)\HTTP_10_Parse.obj \
	$(OBJDIR)\HTTP_10_Write.obj

CFLAGS=-I. -DJAWS_HAS_THREAD_SAFE_ACCEPT
LIBFILES= \
        .\HTTPU$(LIB_DECORATOR).lib \
        .\JAWS$(LIB_DECORATOR).lib \
        $(ACE_LIB)

!include <$(ACE_ROOT)\apps\build.bor>

