#!/usr/bin/perl -w
#This will not work if called from a directory that is not a
#subdirectory of functionalTesting, nor if from functionalTesting itself
open POLICY, ">policy.test" or die "Couldn't open policy.test:$!";
my $purpose;
if ($#ARGV >= 0) {
  $purpose = shift(@ARGV);
} else {
  $purpose = `pwd`;
  chomp($purpose);
  $purpose =~ s/^.*\///;
}
print POLICY "$purpose\n";
print POLICY "# vim".": noexpandtab\n";
#find relative path to eval
my $path = `pwd`;
chomp($path);
$path =~ s/^.*functionalTesting//;
$path =~ s/^\///;
$path =~ s/[^\/]+/../g;
$path = $path."/evaluator";
if ($#ARGV < 0) {@ARGV = ("");};
foreach my $policy (@ARGV) {
  print POLICY "$policy\t";
  print POLICY "$path/eval\t\ttest.xml\n";
}
