

#############################################################################
# Module:           FunctionAPI
# Module Desc:      Lots of Functions
# Project:          Pathan, Open Source X-Path module for Xerces C++
# Project Version:  1
# tmake Template:   pathanSubdir
# Creation Date:    14:44, 2001/09/28
#############################################################################

###### Include macro definitions

MAKEDEFS = ../../Makefile.defs
include $(MAKEDEFS)

###### Files

SOURCES  =	AggregateFunction.cpp \
			NumericFunction.cpp \
			FunctionLookupImpl.cpp \
      DatatypeLookup.cpp \
			ConstantFoldingFunction.cpp

###### Include rules

RULES = ../../Makefile.rules
include $(RULES)
