# $Id: Makefile,v 1.1 2005/07/27 17:56:02 gmf Exp $

###### Include macro definitions

MAKEDEFS = ../../build_unix/Makefile.defs
include $(MAKEDEFS)

###### Files

SOURCES= $(DBXML_DUMP_SOURCES)

###### Include rules

RULES = ../../build_unix/Makefile.rules
include $(RULES)

