

#############################################################################
# Module:           exceptions
# Module Desc:      Exception definitions
# Project:          Pathan, Open Source X-Path module for Xerces C++
# Project Version:  1
# tmake Template:   pathanSubdir
# Creation Date:    14:44, 2001/09/28
#############################################################################

###### Include macro definitions

MAKEDEFS = ../../Makefile.defs
include $(MAKEDEFS)

###### Files

SOURCES     = DSLException.cpp

###### Include rules

RULES = ../../Makefile.rules
include $(RULES)

