#############################################################################
# Module:           utils
# Module Desc:      General utility classes
# Project:          Pathan, Open Source X-Path module for Xerces C++
# Project Version:  1
# tmake Template:   pathanSubdir
# Creation Date:    14:44, 2001/09/28
#############################################################################

###### Include macro definitions

MAKEDEFS = ../../Makefile.defs
include $(MAKEDEFS)

###### Files

SOURCES     = Date.cpp \
              DateUtils.cpp \
              NumUtils.cpp \
              XPath2Utils.cpp \
              XPath2NSUtils.cpp \
              PathanPlatformUtils.cpp \
							PrintDataItemTree.cpp \
							ContextUtils.cpp


###### Include rules

RULES = ../../Makefile.rules
include $(RULES)
