/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sleepycat.dbxml;

import com.sleepycat.db.DatabaseException;

class dbxml_javaJNI {

  static {
    // An alternate library name can be specified via a property.
    //
    String override;

    if ((override = System.getProperty("sleepycat.dbxml.libfile")) != null) {
      System.load(override);
    }
    else if ((override = System.getProperty("sleepycat.dbxml.libname")) != null) {
      System.loadLibrary(override);
    }
    else {
      String os = System.getProperty("os.name");
      if (os != null && os.startsWith("Windows")) {
        // library name is "libdbxml_javaXX.dll" (for example) on Windows
	String libname = "libdbxml_java" +
            XmlConstants.DBXML_VERSION_MAJOR + XmlConstants.DBXML_VERSION_MINOR;
        // add trailing "d" for debug build
	if (XmlConstants.DBXML_DEBUG)
		libname += "d";
        System.loadLibrary(libname);
      }
      else {
        // library name is "libdbxml_java-Major.Minor.so" (for example) on UNIX
        // Note: "dbxml_java" isn't good enough;
        // some Unixes require us to use the explicit SONAME.
        System.loadLibrary("dbxml_java-" +
                   XmlConstants.DBXML_VERSION_MAJOR + "." +
                   XmlConstants.DBXML_VERSION_MINOR);
      }
    }

    initialize();
  }

  static native final void initialize();

  public final static native long new_XmlManager(com.sleepycat.db.internal.DbEnv jarg1, int jarg2);
  public final static native void delete_XmlManager(long jarg1);
  public final static native void XmlManager_setDefaultPageSize(long jarg1, int jarg2);
  public final static native int XmlManager_getDefaultPageSize(long jarg1);
  public final static native void XmlManager_setDefaultSequenceIncrement(long jarg1, int jarg2);
  public final static native int XmlManager_getDefaultSequenceIncrement(long jarg1);
  public final static native void XmlManager_setDefaultContainerType(long jarg1, int jarg2);
  public final static native int XmlManager_getDefaultContainerType(long jarg1);
  public final static native String XmlManager_getHome(long jarg1);
  public final static native void XmlManager_registerResolver(long jarg1, long jarg2);
  public final static native int XmlManager_existsContainer(long jarg1, String jarg2);
  /* package */ final static native void XmlManager_removeContainer__SWIG_0(long jarg1, String jarg2);
  public final static native void XmlManager_removeContainer__SWIG_1(long jarg1, long jarg2, String jarg3);
  /* package */ final static native void XmlManager_renameContainer__SWIG_0(long jarg1, String jarg2, String jarg3);
  public final static native void XmlManager_renameContainer__SWIG_1(long jarg1, long jarg2, String jarg3, String jarg4);
  public final static native void XmlManager_upgradeContainer(long jarg1, String jarg2, long jarg3);
  /* package */ final static native void XmlManager_reindexContainer__SWIG_0(long jarg1, String jarg2, long jarg3, int jarg4);
  public final static native void XmlManager_reindexContainer__SWIG_1(long jarg1, String jarg2, long jarg3);
  public final static native void XmlManager_reindexContainer__SWIG_2(long jarg1, long jarg2, String jarg3, long jarg4, int jarg5);
  public final static native void XmlManager_reindexContainer__SWIG_3(long jarg1, long jarg2, String jarg3, long jarg4);
  public final static native long XmlManager_createStdInInputStream(long jarg1);
  public final static native long XmlManager_createLocalFileInputStream(long jarg1, String jarg2);
  /* package */ final static native long XmlManager_createMemBufInputStream__SWIG_0(long jarg1, String jarg2, long jarg3, String jarg4, boolean jarg5);
  public final static native long XmlManager_createMemBufInputStream__SWIG_1(long jarg1, String jarg2, long jarg3, String jarg4);
  public final static native long XmlManager_createMemBufInputStream__SWIG_2(long jarg1, String jarg2, long jarg3, boolean jarg4);
  /* package */ final static native long XmlManager_createURLInputStream__SWIG_0(long jarg1, String jarg2, String jarg3, String jarg4);
  public final static native long XmlManager_createURLInputStream__SWIG_1(long jarg1, String jarg2, String jarg3);
  /* package */ final static native long XmlManager_createContainer__SWIG_0(long jarg1, String jarg2, int jarg3, int jarg4, int jarg5);
  public final static native long XmlManager_createContainer__SWIG_1(long jarg1, String jarg2, int jarg3, int jarg4);
  public final static native long XmlManager_createContainer__SWIG_2(long jarg1, String jarg2, int jarg3);
  public final static native long XmlManager_createContainer__SWIG_3(long jarg1, long jarg2, String jarg3, int jarg4, int jarg5, int jarg6);
  public final static native long XmlManager_createContainer__SWIG_4(long jarg1, long jarg2, String jarg3, int jarg4, int jarg5);
  public final static native long XmlManager_createContainer__SWIG_5(long jarg1, long jarg2, String jarg3, int jarg4);
  /* package */ final static native long XmlManager_openContainer__SWIG_0(long jarg1, String jarg2, int jarg3);
  public final static native long XmlManager_openContainer__SWIG_1(long jarg1, long jarg2, String jarg3, int jarg4);
  public final static native long XmlManager_openContainer__SWIG_2(long jarg1, String jarg2, int jarg3, int jarg4, int jarg5);
  public final static native long XmlManager_openContainer__SWIG_3(long jarg1, String jarg2, int jarg3, int jarg4);
  public final static native long XmlManager_openContainer__SWIG_4(long jarg1, long jarg2, String jarg3, int jarg4, int jarg5, int jarg6);
  public final static native long XmlManager_openContainer__SWIG_5(long jarg1, long jarg2, String jarg3, int jarg4, int jarg5);
  public final static native void XmlManager_dumpContainer(long jarg1, String jarg2, String jarg3);
  public final static native void XmlManager_loadContainer(long jarg1, String jarg2, String jarg3, long jarg4);
  /* package */ final static native void XmlManager_verifyContainer__SWIG_0(long jarg1, String jarg2, String jarg3, int jarg4);
  public final static native void XmlManager_verifyContainer__SWIG_1(long jarg1, String jarg2, String jarg3);
  public final static native long XmlManager_createDocument(long jarg1);
  /* package */ final static native long XmlManager_createQueryContext__SWIG_0(long jarg1, int jarg2, int jarg3);
  public final static native long XmlManager_createQueryContext__SWIG_1(long jarg1);
  public final static native long XmlManager_createQueryContext__SWIG_2(long jarg1, int jarg2);
  public final static native long XmlManager_createUpdateContext(long jarg1);
  /* package */ final static native long XmlManager_prepare__SWIG_0(long jarg1, String jarg2, long jarg3);
  public final static native long XmlManager_prepare__SWIG_1(long jarg1, long jarg2, String jarg3, long jarg4);
  /* package */ final static native long XmlManager_query__SWIG_0(long jarg1, String jarg2, long jarg3, int jarg4);
  public final static native long XmlManager_query__SWIG_1(long jarg1, long jarg2, String jarg3, long jarg4, int jarg5);
  public final static native long XmlManager_query__SWIG_2(long jarg1, String jarg2, long jarg3);
  public final static native long XmlManager_query__SWIG_3(long jarg1, long jarg2, String jarg3, long jarg4);
  public final static native long XmlManager_createResults(long jarg1);
  public final static native long XmlManager_createModify(long jarg1);
  public final static native long XmlManager_createTransaction(long jarg1, com.sleepycat.db.internal.DbTxn jarg2);
  /* package */ final static native long XmlManager_createIndexLookup__SWIG_0(long jarg1, long jarg2, String jarg3, String jarg4, String jarg5, long jarg6, int jarg7);
  public final static native long XmlManager_createIndexLookup__SWIG_1(long jarg1, long jarg2, String jarg3, String jarg4, String jarg5, long jarg6);
  public final static native long XmlManager_createIndexLookup__SWIG_2(long jarg1, long jarg2, String jarg3, String jarg4, String jarg5);
  public final static native void XmlManager_setLogLevel(int jarg1, boolean jarg2);
  public final static native void XmlManager_setLogCategory(int jarg1, boolean jarg2);
  public final static native int XmlManager_get_version_major();
  public final static native int XmlManager_get_version_minor();
  public final static native int XmlManager_get_version_patch();
  public final static native String XmlManager_get_version_string();
  public final static native long new_XmlIndexLookup(long jarg1);
  public final static native void delete_XmlIndexLookup(long jarg1);
  public final static native boolean XmlIndexLookup_isNull(long jarg1);
  public final static native String XmlIndexLookup_getIndex(long jarg1);
  public final static native void XmlIndexLookup_setIndex(long jarg1, String jarg2);
  public final static native String XmlIndexLookup_getNodeURI(long jarg1);
  public final static native String XmlIndexLookup_getNodeName(long jarg1);
  public final static native void XmlIndexLookup_setNode(long jarg1, String jarg2, String jarg3);
  public final static native String XmlIndexLookup_getParentURI(long jarg1);
  public final static native String XmlIndexLookup_getParentName(long jarg1);
  public final static native void XmlIndexLookup_setParent(long jarg1, String jarg2, String jarg3);
  public final static native long XmlIndexLookup_getLowBoundValue(long jarg1);
  public final static native int XmlIndexLookup_getLowBoundOperation(long jarg1);
  public final static native void XmlIndexLookup_setLowBound(long jarg1, long jarg2, int jarg3);
  public final static native long XmlIndexLookup_getHighBoundValue(long jarg1);
  public final static native int XmlIndexLookup_getHighBoundOperation(long jarg1);
  public final static native void XmlIndexLookup_setHighBound(long jarg1, long jarg2, int jarg3);
  public final static native long XmlIndexLookup_getContainer(long jarg1);
  public final static native void XmlIndexLookup_setContainer(long jarg1, long jarg2);
  /* package */ final static native long XmlIndexLookup_execute__SWIG_0(long jarg1, long jarg2, int jarg3);
  public final static native long XmlIndexLookup_execute__SWIG_1(long jarg1, long jarg2);
  public final static native long XmlIndexLookup_execute__SWIG_2(long jarg1, long jarg2, long jarg3, int jarg4);
  public final static native long XmlIndexLookup_execute__SWIG_3(long jarg1, long jarg2, long jarg3);
  public final static native long new_XmlContainer(long jarg1);
  public final static native void delete_XmlContainer(long jarg1);
  public final static native void XmlContainer_sync(long jarg1);
  public final static native boolean XmlContainer_addAlias(long jarg1, String jarg2);
  public final static native boolean XmlContainer_removeAlias(long jarg1, String jarg2);
  public final static native long XmlContainer_getManager(long jarg1);
  public final static native String XmlContainer_getName(long jarg1);
  public final static native int XmlContainer_getContainerType(long jarg1);
  public final static native boolean XmlContainer_getIndexNodes(long jarg1);
  public final static native int XmlContainer_getPageSize(long jarg1);
  /* package */ final static native void XmlContainer_setIndexSpecification__SWIG_0(long jarg1, long jarg2, long jarg3);
  /* package */ final static native void XmlContainer_addIndex__SWIG_0(long jarg1, String jarg2, String jarg3, String jarg4, long jarg5);
  public final static native void XmlContainer_addIndex__SWIG_1(long jarg1, String jarg2, String jarg3, int jarg4, int jarg5, long jarg6);
  /* package */ final static native void XmlContainer_deleteIndex__SWIG_0(long jarg1, String jarg2, String jarg3, String jarg4, long jarg5);
  /* package */ final static native void XmlContainer_replaceIndex__SWIG_0(long jarg1, String jarg2, String jarg3, String jarg4, long jarg5);
  /* package */ final static native void XmlContainer_addDefaultIndex__SWIG_0(long jarg1, String jarg2, long jarg3);
  /* package */ final static native void XmlContainer_deleteDefaultIndex__SWIG_0(long jarg1, String jarg2, long jarg3);
  /* package */ final static native void XmlContainer_replaceDefaultIndex__SWIG_0(long jarg1, String jarg2, long jarg3);
  public final static native void XmlContainer_setIndexSpecification__SWIG_1(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native void XmlContainer_addIndex__SWIG_2(long jarg1, long jarg2, String jarg3, String jarg4, String jarg5, long jarg6);
  public final static native void XmlContainer_addIndex__SWIG_3(long jarg1, long jarg2, String jarg3, String jarg4, int jarg5, int jarg6, long jarg7);
  public final static native void XmlContainer_deleteIndex__SWIG_1(long jarg1, long jarg2, String jarg3, String jarg4, String jarg5, long jarg6);
  public final static native void XmlContainer_replaceIndex__SWIG_1(long jarg1, long jarg2, String jarg3, String jarg4, String jarg5, long jarg6);
  public final static native void XmlContainer_addDefaultIndex__SWIG_1(long jarg1, long jarg2, String jarg3, long jarg4);
  public final static native void XmlContainer_deleteDefaultIndex__SWIG_1(long jarg1, long jarg2, String jarg3, long jarg4);
  public final static native void XmlContainer_replaceDefaultIndex__SWIG_1(long jarg1, long jarg2, String jarg3, long jarg4);
  /* package */ final static native void XmlContainer_putDocument__SWIG_0(long jarg1, long jarg2, long jarg3, int jarg4);
  public final static native void XmlContainer_putDocument__SWIG_1(long jarg1, long jarg2, long jarg3);
  public final static native String XmlContainer_putDocument__SWIG_2(long jarg1, String jarg2, String jarg3, long jarg4, int jarg5);
  public final static native String XmlContainer_putDocument__SWIG_3(long jarg1, String jarg2, String jarg3, long jarg4);
  /* package */ final static native void XmlContainer_deleteDocument__SWIG_0(long jarg1, long jarg2, long jarg3);
  public final static native void XmlContainer_deleteDocument__SWIG_1(long jarg1, String jarg2, long jarg3);
  /* package */ final static native void XmlContainer_updateDocument__SWIG_0(long jarg1, long jarg2, long jarg3);
  public final static native String XmlContainer_putDocument__SWIG_4(long jarg1, String jarg2, long jarg3, long jarg4, int jarg5);
  public final static native String XmlContainer_putDocument__SWIG_5(long jarg1, String jarg2, long jarg3, long jarg4);
  public final static native String XmlContainer_putDocument__SWIG_6(long jarg1, long jarg2, String jarg3, long jarg4, long jarg5, int jarg6);
  public final static native String XmlContainer_putDocument__SWIG_7(long jarg1, long jarg2, String jarg3, long jarg4, long jarg5);
  public final static native void XmlContainer_putDocument__SWIG_8(long jarg1, long jarg2, long jarg3, long jarg4, int jarg5);
  public final static native void XmlContainer_putDocument__SWIG_9(long jarg1, long jarg2, long jarg3, long jarg4);
  /* package */ final static native String XmlContainer_putDocument__SWIG_10(long jarg1, long jarg2, String jarg3, String jarg4, long jarg5, int jarg6);
  public final static native String XmlContainer_putDocument__SWIG_11(long jarg1, long jarg2, String jarg3, String jarg4, long jarg5);
  public final static native void XmlContainer_deleteDocument__SWIG_2(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native void XmlContainer_deleteDocument__SWIG_3(long jarg1, long jarg2, String jarg3, long jarg4);
  public final static native void XmlContainer_updateDocument__SWIG_1(long jarg1, long jarg2, long jarg3, long jarg4);
  /* package */ final static native int XmlContainer_getNumDocuments__SWIG_0(long jarg1);
  public final static native int XmlContainer_getNumDocuments__SWIG_1(long jarg1, long jarg2);
  /* package */ final static native long XmlContainer_getIndexSpecification__SWIG_0(long jarg1);
  public final static native long XmlContainer_getIndexSpecification__SWIG_1(long jarg1, long jarg2);
  public final static native long XmlContainer_getIndexSpecification__SWIG_2(long jarg1, long jarg2, int jarg3);
  /* package */ final static native long XmlContainer_getDocument__SWIG_0(long jarg1, String jarg2, int jarg3);
  public final static native long XmlContainer_getDocument__SWIG_1(long jarg1, long jarg2, String jarg3, int jarg4);
  /* package */ final static native long XmlContainer_getAllDocuments__SWIG_0(long jarg1, int jarg2);
  public final static native long XmlContainer_getAllDocuments__SWIG_1(long jarg1, long jarg2, int jarg3);
  /* package */ final static native long XmlContainer_lookupIndex__SWIG_0(long jarg1, long jarg2, String jarg3, String jarg4, String jarg5, long jarg6, int jarg7);
  public final static native long XmlContainer_lookupIndex__SWIG_1(long jarg1, long jarg2, String jarg3, String jarg4, String jarg5, long jarg6);
  public final static native long XmlContainer_lookupIndex__SWIG_2(long jarg1, long jarg2, String jarg3, String jarg4, String jarg5);
  public final static native long XmlContainer_lookupIndex__SWIG_3(long jarg1, long jarg2, String jarg3, String jarg4, String jarg5, String jarg6, String jarg7, long jarg8, int jarg9);
  public final static native long XmlContainer_lookupIndex__SWIG_4(long jarg1, long jarg2, String jarg3, String jarg4, String jarg5, String jarg6, String jarg7, long jarg8);
  public final static native long XmlContainer_lookupIndex__SWIG_5(long jarg1, long jarg2, String jarg3, String jarg4, String jarg5, String jarg6, String jarg7);
  public final static native long XmlContainer_lookupIndex__SWIG_6(long jarg1, long jarg2, long jarg3, String jarg4, String jarg5, String jarg6, long jarg7, int jarg8);
  public final static native long XmlContainer_lookupIndex__SWIG_7(long jarg1, long jarg2, long jarg3, String jarg4, String jarg5, String jarg6, long jarg7);
  public final static native long XmlContainer_lookupIndex__SWIG_8(long jarg1, long jarg2, long jarg3, String jarg4, String jarg5, String jarg6);
  public final static native long XmlContainer_lookupIndex__SWIG_9(long jarg1, long jarg2, long jarg3, String jarg4, String jarg5, String jarg6, String jarg7, String jarg8, long jarg9, int jarg10);
  /* package */ final static native long XmlContainer_lookupIndex__SWIG_10(long jarg1, long jarg2, long jarg3, String jarg4, String jarg5, String jarg6, String jarg7, String jarg8, long jarg9);
  public final static native long XmlContainer_lookupIndex__SWIG_11(long jarg1, long jarg2, long jarg3, String jarg4, String jarg5, String jarg6, String jarg7, String jarg8);
  /* package */ final static native long XmlContainer_lookupStatistics__SWIG_0(long jarg1, String jarg2, String jarg3, String jarg4, long jarg5);
  public final static native long XmlContainer_lookupStatistics__SWIG_1(long jarg1, String jarg2, String jarg3, String jarg4);
  public final static native long XmlContainer_lookupStatistics__SWIG_2(long jarg1, String jarg2, String jarg3, String jarg4, String jarg5, String jarg6, long jarg7);
  public final static native long XmlContainer_lookupStatistics__SWIG_3(long jarg1, String jarg2, String jarg3, String jarg4, String jarg5, String jarg6);
  public final static native long XmlContainer_lookupStatistics__SWIG_4(long jarg1, long jarg2, String jarg3, String jarg4, String jarg5, long jarg6);
  public final static native long XmlContainer_lookupStatistics__SWIG_5(long jarg1, long jarg2, String jarg3, String jarg4, String jarg5);
  public final static native long XmlContainer_lookupStatistics__SWIG_6(long jarg1, long jarg2, String jarg3, String jarg4, String jarg5, String jarg6, String jarg7, long jarg8);
  public final static native long XmlContainer_lookupStatistics__SWIG_7(long jarg1, long jarg2, String jarg3, String jarg4, String jarg5, String jarg6, String jarg7);
  public final static native void XmlContainer_closeContainer(long jarg1);
  public final static native long new_XmlDocument(long jarg1);
  public final static native void delete_XmlDocument(long jarg1);
  public final static native void XmlDocument_setName(long jarg1, String jarg2);
  public final static native String XmlDocument_getName(long jarg1);
  /* package */ final static native void XmlDocument_setContent__SWIG_0(long jarg1, String jarg2);
  public final static native void XmlDocument_setContent__SWIG_1(long jarg1, byte[] jarg2);
  public final static native long XmlDocument_getContentAsXmlInputStream(long jarg1);
  public final static native void XmlDocument_setContentAsXmlInputStream(long jarg1, long jarg2);
  public final static native void XmlDocument_fetchAllData(long jarg1);
  /* package */ final static native void XmlDocument_setMetaData__SWIG_0(long jarg1, String jarg2, String jarg3, long jarg4);
  /* package */ final static native boolean XmlDocument_getMetaData__SWIG_0(long jarg1, String jarg2, String jarg3, long jarg4);
  public final static native void XmlDocument_removeMetaData(long jarg1, String jarg2, String jarg3);
  public final static native void XmlDocument_setMetaData__SWIG_1(long jarg1, String jarg2, String jarg3, byte[] jarg4);
  public final static native String XmlDocument_getContentAsString(long jarg1);
  public final static native byte[] XmlDocument_getContent(long jarg1);
  public final static native byte[] XmlDocument_getMetaData__SWIG_1(long jarg1, String jarg2, String jarg3);
  public final static native long XmlDocument_getMetaDataIterator(long jarg1);
  public final static native long new_XmlMetaDataIterator(long jarg1);
  public final static native void delete_XmlMetaDataIterator(long jarg1);
  public final static native void XmlMetaDataIterator_reset(long jarg1);
  public final static native long XmlMetaDataIterator_next(long jarg1);
  public final static native void delete_XmlMetaData(long jarg1);
  public final static native String XmlMetaData_get_uri(long jarg1);
  public final static native String XmlMetaData_get_name(long jarg1);
  public final static native long XmlMetaData_get_value(long jarg1);
  public final static native long new_XmlQueryContext(long jarg1);
  public final static native void delete_XmlQueryContext(long jarg1);
  public final static native void XmlQueryContext_setNamespace(long jarg1, String jarg2, String jarg3);
  public final static native String XmlQueryContext_getNamespace(long jarg1, String jarg2);
  public final static native void XmlQueryContext_removeNamespace(long jarg1, String jarg2);
  public final static native void XmlQueryContext_clearNamespaces(long jarg1);
  /* package */ final static native void XmlQueryContext_setVariableValue__SWIG_0(long jarg1, String jarg2, long jarg3);
  public final static native void XmlQueryContext_setVariableValue__SWIG_1(long jarg1, String jarg2, long jarg3);
  public final static native void XmlQueryContext_setBaseURI(long jarg1, String jarg2);
  public final static native String XmlQueryContext_getBaseURI(long jarg1);
  public final static native void XmlQueryContext_setReturnType(long jarg1, int jarg2);
  public final static native int XmlQueryContext_getReturnType(long jarg1);
  public final static native void XmlQueryContext_setEvaluationType(long jarg1, int jarg2);
  public final static native int XmlQueryContext_getEvaluationType(long jarg1);
  public final static native void XmlQueryContext_setDefaultCollection(long jarg1, String jarg2);
  public final static native String XmlQueryContext_getDefaultCollection(long jarg1);
  public final static native long XmlQueryContext_getVariableValue(long jarg1, String jarg2);
  public final static native long XmlQueryContext_getVariableValues(long jarg1, String jarg2);
  public final static native void delete_XmlResults(long jarg1);
  public final static native long new_XmlResults(long jarg1);
  public final static native boolean XmlResults_hasNext(long jarg1);
  public final static native boolean XmlResults_hasPrevious(long jarg1);
  /* package */ final static native long XmlResults_next__SWIG_0(long jarg1);
  /* package */ final static native long XmlResults_previous__SWIG_0(long jarg1);
  /* package */ final static native long XmlResults_peek__SWIG_0(long jarg1);
  public final static native boolean XmlResults_next__SWIG_1(long jarg1, long jarg2);
  public final static native boolean XmlResults_previous__SWIG_1(long jarg1, long jarg2);
  public final static native boolean XmlResults_peek__SWIG_1(long jarg1, long jarg2);
  public final static native void XmlResults_reset(long jarg1);
  public final static native int XmlResults_size(long jarg1);
  public final static native void XmlResults_add(long jarg1, long jarg2);
  public final static native long new_XmlUpdateContext(long jarg1);
  public final static native void delete_XmlUpdateContext(long jarg1);
  public final static native void XmlUpdateContext_setApplyChangesToContainers(long jarg1, boolean jarg2);
  public final static native boolean XmlUpdateContext_getApplyChangesToContainers(long jarg1);
  /* package */ final static native long new_XmlValue__SWIG_0();
  public final static native long new_XmlValue__SWIG_1(long jarg1);
  public final static native long new_XmlValue__SWIG_2(String jarg1);
  public final static native long new_XmlValue__SWIG_3(double jarg1);
  public final static native long new_XmlValue__SWIG_4(boolean jarg1);
  public final static native long new_XmlValue__SWIG_5(long jarg1);
  public final static native long new_XmlValue__SWIG_6(int jarg1, String jarg2);
  public final static native long new_XmlValue__SWIG_7(int jarg1, byte[] jarg2);
  public final static native void delete_XmlValue(long jarg1);
  public final static native int XmlValue_getType(long jarg1);
  public final static native boolean XmlValue_isNull(long jarg1);
  public final static native boolean XmlValue_isType(long jarg1, int jarg2);
  public final static native boolean XmlValue_isNumber(long jarg1);
  public final static native boolean XmlValue_isString(long jarg1);
  public final static native boolean XmlValue_isBoolean(long jarg1);
  public final static native boolean XmlValue_isBinary(long jarg1);
  public final static native boolean XmlValue_isNode(long jarg1);
  public final static native double XmlValue_asNumber(long jarg1);
  /* package */ final static native String XmlValue_asString__SWIG_0(long jarg1);
  public final static native String XmlValue_asString__SWIG_1(long jarg1, String jarg2);
  public final static native boolean XmlValue_asBoolean(long jarg1);
  public final static native byte[] XmlValue_asBinary(long jarg1);
  public final static native long XmlValue_asDocument(long jarg1);
  public final static native boolean XmlValue_equals(long jarg1, long jarg2);
  public final static native String XmlValue_getNodeName(long jarg1);
  public final static native String XmlValue_getNodeValue(long jarg1);
  public final static native String XmlValue_getNamespaceURI(long jarg1);
  public final static native String XmlValue_getPrefix(long jarg1);
  public final static native String XmlValue_getLocalName(long jarg1);
  public final static native short XmlValue_getNodeType(long jarg1);
  public final static native long XmlValue_getParentNode(long jarg1);
  public final static native long XmlValue_getFirstChild(long jarg1);
  public final static native long XmlValue_getLastChild(long jarg1);
  public final static native long XmlValue_getPreviousSibling(long jarg1);
  public final static native long XmlValue_getNextSibling(long jarg1);
  public final static native long XmlValue_getAttributes(long jarg1);
  public final static native long XmlValue_getOwnerElement(long jarg1);
  public final static native void XmlValue_setValue(long jarg1, long jarg2);
  public final static native void delete_XmlIndexSpecification(long jarg1);
  /* package */ final static native void XmlIndexSpecification_addIndex__SWIG_0(long jarg1, String jarg2, String jarg3, int jarg4, int jarg5);
  public final static native void XmlIndexSpecification_addIndex__SWIG_1(long jarg1, String jarg2, String jarg3, String jarg4);
  /* package */ final static native void XmlIndexSpecification_deleteIndex__SWIG_0(long jarg1, String jarg2, String jarg3, int jarg4, int jarg5);
  public final static native void XmlIndexSpecification_deleteIndex__SWIG_1(long jarg1, String jarg2, String jarg3, String jarg4);
  /* package */ final static native void XmlIndexSpecification_replaceIndex__SWIG_0(long jarg1, String jarg2, String jarg3, int jarg4, int jarg5);
  public final static native void XmlIndexSpecification_replaceIndex__SWIG_1(long jarg1, String jarg2, String jarg3, String jarg4);
  /* package */ final static native void XmlIndexSpecification_addDefaultIndex__SWIG_0(long jarg1, int jarg2, int jarg3);
  public final static native void XmlIndexSpecification_addDefaultIndex__SWIG_1(long jarg1, String jarg2);
  /* package */ final static native void XmlIndexSpecification_deleteDefaultIndex__SWIG_0(long jarg1, int jarg2, int jarg3);
  public final static native void XmlIndexSpecification_deleteDefaultIndex__SWIG_1(long jarg1, String jarg2);
  /* package */ final static native void XmlIndexSpecification_replaceDefaultIndex__SWIG_0(long jarg1, int jarg2, int jarg3);
  public final static native void XmlIndexSpecification_replaceDefaultIndex__SWIG_1(long jarg1, String jarg2);
  public final static native void XmlIndexSpecification_reset(long jarg1);
  public final static native XmlIndexDeclaration XmlIndexSpecification_find(long jarg1, String jarg2, String jarg3);
  public final static native XmlIndexDeclaration XmlIndexSpecification_next(long jarg1);
  public final static native String XmlIndexSpecification_getDefaultIndex(long jarg1);
  public final static native int XmlIndexSpecification_getValueType(String jarg1);
  public final static native long new_XmlQueryExpression(long jarg1);
  public final static native void delete_XmlQueryExpression(long jarg1);
  public final static native String XmlQueryExpression_getQuery(long jarg1);
  public final static native String XmlQueryExpression_getQueryPlan(long jarg1);
  /* package */ final static native long XmlQueryExpression_execute__SWIG_0(long jarg1, long jarg2, int jarg3);
  public final static native long XmlQueryExpression_execute__SWIG_1(long jarg1, long jarg2);
  public final static native long XmlQueryExpression_execute__SWIG_2(long jarg1, long jarg2, long jarg3, int jarg4);
  public final static native long XmlQueryExpression_execute__SWIG_3(long jarg1, long jarg2, long jarg3);
  public final static native long XmlQueryExpression_execute__SWIG_4(long jarg1, long jarg2, long jarg3, int jarg4);
  public final static native long XmlQueryExpression_execute__SWIG_5(long jarg1, long jarg2, long jarg3);
  public final static native long XmlQueryExpression_execute__SWIG_6(long jarg1, long jarg2, long jarg3, long jarg4, int jarg5);
  public final static native long XmlQueryExpression_execute__SWIG_7(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native long new_XmlInputStream();
  public final static native void XmlInputStream_director_connect(XmlInputStream obj, long cptr);
  public final static native void delete_XmlInputStream(long jarg1);
  public final static native long XmlInputStream_curPos(long jarg1);
  public final static native long XmlInputStream_readBytes(long jarg1, byte[] jarg2, long jarg3);
  public final static native void XmlInputStream_freeMemory(long jarg1);
  public final static native long new_XmlResolver();
  public final static native void XmlResolver_director_connect(XmlResolver obj, long cptr);
  public final static native void delete_XmlResolver(long jarg1);
  public final static native boolean XmlResolver_resolveDocument(long jarg1, long jarg2, long jarg3, String jarg4, long jarg5);
  public final static native boolean XmlResolver_resolveCollection(long jarg1, long jarg2, long jarg3, String jarg4, long jarg5);
  public final static native long XmlResolver_resolveSchema(long jarg1, long jarg2, long jarg3, String jarg4, String jarg5);
  public final static native long XmlResolver_resolveEntity(long jarg1, long jarg2, long jarg3, String jarg4, String jarg5);
  public final static native long new_XmlModify(long jarg1);
  public final static native void delete_XmlModify(long jarg1);
  public final static native void XmlModify_addInsertBeforeStep(long jarg1, long jarg2, int jarg3, String jarg4, String jarg5);
  public final static native void XmlModify_addInsertAfterStep(long jarg1, long jarg2, int jarg3, String jarg4, String jarg5);
  /* package */ final static native void XmlModify_addAppendStep__SWIG_0(long jarg1, long jarg2, int jarg3, String jarg4, String jarg5, int jarg6);
  public final static native void XmlModify_addAppendStep__SWIG_1(long jarg1, long jarg2, int jarg3, String jarg4, String jarg5);
  public final static native void XmlModify_addUpdateStep(long jarg1, long jarg2, String jarg3);
  public final static native void XmlModify_addRemoveStep(long jarg1, long jarg2);
  public final static native void XmlModify_addRenameStep(long jarg1, long jarg2, String jarg3);
  public final static native void XmlModify_setNewEncoding(long jarg1, String jarg2);
  /* package */ final static native long XmlModify_execute__SWIG_0(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native long XmlModify_execute__SWIG_1(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native long XmlModify_execute__SWIG_2(long jarg1, long jarg2, long jarg3, long jarg4, long jarg5);
  public final static native long XmlModify_execute__SWIG_3(long jarg1, long jarg2, long jarg3, long jarg4, long jarg5);
  public final static native void delete_XmlTransaction(long jarg1);
  public final static native long new_XmlStatistics(long jarg1);
  public final static native void delete_XmlStatistics(long jarg1);
  public final static native double XmlStatistics_getNumberOfIndexedKeys(long jarg1);
  public final static native double XmlStatistics_getNumberOfUniqueKeys(long jarg1);
  public final static native double XmlStatistics_getSumKeyValueSize(long jarg1);

/* Director upcall methods: */

public static long SwigDirector_XmlInputStream_curPos(XmlInputStream self) throws XmlException {
    return self.curPos();
}

public static long SwigDirector_XmlInputStream_readBytes(XmlInputStream self, byte[] toFill, long maxToRead) throws XmlException {
    return self.readBytes(toFill, maxToRead);
}

public static boolean SwigDirector_XmlResolver_resolveDocument(XmlResolver self, long txn, long mgr, String uri, long res) throws XmlException {
    return self.resolveDocument(new XmlTransaction(txn, false), new XmlManager(mgr, false), uri, new XmlValue(res, false));
}

public static boolean SwigDirector_XmlResolver_resolveCollection(XmlResolver self, long txn, long mgr, String uri, long res) throws XmlException {
    return self.resolveCollection(new XmlTransaction(txn, false), new XmlManager(mgr, false), uri, new XmlResults(res, false));
}

public static long SwigDirector_XmlResolver_resolveSchema(XmlResolver self, long txn, long mgr, String schemaLocation, String nameSpace) throws XmlException {
    return XmlInputStream.getCPtr(self.resolveSchema(new XmlTransaction(txn, false), new XmlManager(mgr, false), schemaLocation, nameSpace));
}

public static long SwigDirector_XmlResolver_resolveEntity(XmlResolver self, long txn, long mgr, String systemId, String publicId) throws XmlException {
    return XmlInputStream.getCPtr(self.resolveEntity(new XmlTransaction(txn, false), new XmlManager(mgr, false), systemId, publicId));
}


  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
