/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sleepycat.dbxml;

import com.sleepycat.db.*;
import com.sleepycat.db.internal.DbEnv;
import com.sleepycat.db.internal.DbConstants;
import java.io.InputStream;

public class XmlDocument {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected XmlDocument(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XmlDocument obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected XmlDocument() {
    this(0, false);
  }

  protected void finalize() {
    delete();
  }

  public void delete() /* no exception */ {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      dbxml_javaJNI.delete_XmlDocument(swigCPtr);
    }
    swigCPtr = 0;
  }

    public InputStream getContentAsInputStream() throws XmlException {
	return new XmlInputStreamWrap(getContentAsXmlInputStream());
    }

  public XmlDocument(XmlDocument o) throws XmlException {
    this(dbxml_javaJNI.new_XmlDocument(XmlDocument.getCPtr(o)), true);
  }

  public void setName(String name) throws XmlException {
    dbxml_javaJNI.XmlDocument_setName(swigCPtr, name);
  }

  public String getName() throws XmlException {
    return dbxml_javaJNI.XmlDocument_getName(swigCPtr);
  }

  public void setContent(String content) throws XmlException {
    dbxml_javaJNI.XmlDocument_setContent__SWIG_0(swigCPtr, content);
  }

  public void setContent(byte[] content) throws XmlException {
    dbxml_javaJNI.XmlDocument_setContent__SWIG_1(swigCPtr, content);
  }

  public XmlInputStream getContentAsXmlInputStream() throws XmlException {
    long cPtr = dbxml_javaJNI.XmlDocument_getContentAsXmlInputStream(swigCPtr);
    return (cPtr == 0) ? null : new XmlInputStream(cPtr, true);
  }

  public void setContentAsXmlInputStream(XmlInputStream adopted) throws XmlException {
    dbxml_javaJNI.XmlDocument_setContentAsXmlInputStream(swigCPtr, XmlInputStream.getCPtr(adopted));
  }

  public void fetchAllData() throws XmlException {
    dbxml_javaJNI.XmlDocument_fetchAllData(swigCPtr);
  }

  public void setMetaData(String uri, String name, XmlValue value) throws XmlException {
    dbxml_javaJNI.XmlDocument_setMetaData__SWIG_0(swigCPtr, uri, name, XmlValue.getCPtr(value));
  }

  public boolean getMetaData(String uri, String name, XmlValue value) throws XmlException {
    return dbxml_javaJNI.XmlDocument_getMetaData__SWIG_0(swigCPtr, uri, name, XmlValue.getCPtr(value));
  }

  public void removeMetaData(String uri, String name) throws XmlException {
    dbxml_javaJNI.XmlDocument_removeMetaData(swigCPtr, uri, name);
  }

  public void setMetaData(String uri, String name, byte[] value) throws XmlException {
    dbxml_javaJNI.XmlDocument_setMetaData__SWIG_1(swigCPtr, uri, name, value);
  }

  public String getContentAsString() throws XmlException {
    return dbxml_javaJNI.XmlDocument_getContentAsString(swigCPtr);
  }

  public byte[] getContent() throws XmlException { return dbxml_javaJNI.XmlDocument_getContent(swigCPtr); }

  public byte[] getMetaData(String uri, String name) throws XmlException { return dbxml_javaJNI.XmlDocument_getMetaData__SWIG_1(swigCPtr, uri, name); }

  public XmlMetaDataIterator getMetaDataIterator() throws XmlException {
    long cPtr = dbxml_javaJNI.XmlDocument_getMetaDataIterator(swigCPtr);
    return (cPtr == 0) ? null : new XmlMetaDataIterator(cPtr, true);
  }

}
