

#############################################################################
# Module:           Date/Time Functions
# Module Desc:      XPath2 Functions
# Project:          Pathan, Open Source X-Path module for Xerces C++
# Project Version:  1
# tmake Template:   pathanSubdir
# Creation Date:    14:44, 2001/09/28
#############################################################################

###### Include macro definitions

MAKEDEFS = ../../../Makefile.defs
include $(MAKEDEFS)

###### Files

SOURCES    =  FunctionYearsFromDuration.cpp \
              FunctionMonthsFromDuration.cpp \
              FunctionDaysFromDuration.cpp \
              FunctionHoursFromDuration.cpp \
              FunctionMinutesFromDuration.cpp \
              FunctionSecondsFromDuration.cpp \
              FunctionYearFromDateTime.cpp \
              FunctionMonthFromDateTime.cpp \
              FunctionDayFromDateTime.cpp \
              FunctionHoursFromDateTime.cpp \
              FunctionMinutesFromDateTime.cpp \
              FunctionSecondsFromDateTime.cpp \
              FunctionTimezoneFromDateTime.cpp \
              FunctionYearFromDate.cpp \
              FunctionMonthFromDate.cpp \
              FunctionDayFromDate.cpp \
              FunctionTimezoneFromDate.cpp \
              FunctionHoursFromTime.cpp \
              FunctionMinutesFromTime.cpp \
              FunctionSecondsFromTime.cpp \
              FunctionTimezoneFromTime.cpp \
              FunctionAdjustDateTimeToTimezone.cpp \
              FunctionAdjustDateToTimezone.cpp \
              FunctionAdjustTimeToTimezone.cpp


###### Include rules

RULES = ../../../Makefile.rules
include $(RULES)
