

#############################################################################
# Module:           Functions
# Module Desc:      XPath2 Functions
# Project:          Pathan, Open Source X-Path module for Xerces C++
# Project Version:  1
# tmake Template:   pathanSubdir
# Creation Date:    14:44, 2001/09/28
#############################################################################

###### Include macro definitions

MAKEDEFS = ../../Makefile.defs
include $(MAKEDEFS)

###### Files

SOURCES     =   FunctionAbs.cpp \
				FunctionAvg.cpp \
				FunctionBoolean.cpp \
				FunctionBaseURI.cpp \
				FunctionCeiling.cpp \
				FunctionCodepointEqual.cpp \
				FunctionCodepointsToString.cpp \
				FunctionCollection.cpp \
				FunctionCompare.cpp \
				FunctionConcat.cpp \
				FunctionConstructor.cpp \
				FunctionContains.cpp \
				FunctionCount.cpp \
				FunctionCurrentDate.cpp \
				FunctionCurrentDateTime.cpp \
				FunctionCurrentTime.cpp \
				FunctionData.cpp \
				FunctionDateTime.cpp \
				FunctionDeepEqual.cpp \
				FunctionDefaultCollation.cpp \
				FunctionDistinctValues.cpp \
				FunctionDoc.cpp \
				FunctionDocAvailable.cpp \
				FunctionDocumentURI.cpp \
				FunctionEmpty.cpp \
				FunctionEndsWith.cpp \
				FunctionError.cpp \
				FunctionEscapeURI.cpp \
				FunctionExactlyOne.cpp \
				FunctionExists.cpp \
				FunctionFalse.cpp \
				FunctionFloor.cpp \
				FunctionId.cpp \
				FunctionIdref.cpp \
				FunctionImplicitTimezone.cpp \
				FunctionInScopePrefixes.cpp \
				FunctionInsertBefore.cpp \
				FunctionIndexOf.cpp \
				FunctionLang.cpp \
				FunctionLast.cpp \
				FunctionLocalname.cpp \
				FunctionLocalNameFromQName.cpp \
				FunctionLowerCase.cpp \
				FunctionMatches.cpp \
				FunctionMax.cpp \
				FunctionMin.cpp \
				FunctionName.cpp \
				FunctionNamespaceUri.cpp \
				FunctionNamespaceURIFromQName.cpp \
				FunctionNamespaceURIForPrefix.cpp \
				FunctionNilled.cpp \
				FunctionNodeName.cpp \
				FunctionNormalizeSpace.cpp \
				FunctionNormalizeUnicode.cpp \
				FunctionNot.cpp \
				FunctionNumber.cpp \
				FunctionOneOrMore.cpp \
				FunctionPosition.cpp \
				FunctionPrefixFromQName.cpp \
				FunctionQName.cpp \
				FunctionRemove.cpp \
				FunctionReplace.cpp \
				FunctionResolveQName.cpp \
				FunctionResolveURI.cpp \
				FunctionReverse.cpp \
				FunctionRound.cpp \
				FunctionRoundHalfToEven.cpp \
				FunctionRoot.cpp \
				FunctionStartsWith.cpp \
				FunctionStaticBaseURI.cpp \
				FunctionString.cpp \
				FunctionStringJoin.cpp \
				FunctionStringLength.cpp \
				FunctionStringToCodepoints.cpp \
				FunctionSubsequence.cpp \
				FunctionSubstring.cpp \
				FunctionSubstringAfter.cpp \
				FunctionSubstringBefore.cpp \
				FunctionSum.cpp \
				FunctionTokenize.cpp \
				FunctionTrace.cpp \
				FunctionTranslate.cpp \
				FunctionTrue.cpp \
				FunctionUnordered.cpp \
				FunctionUpperCase.cpp \
				FunctionZeroOrOne.cpp \

###### Include rules

RULES = ../../Makefile.rules
include $(RULES)
