# $Id: Makefile,v 1.2 2006/06/13 19:33:40 gmf Exp $

###### Include macro definitions

MAKEDEFS = $(builddir)/Makefile.defs
include $(MAKEDEFS)

###### Files

SOURCES= $(UNIT_TEST_QPAPI_SOURCES)

###### Include rules

RULES = $(builddir)/Makefile.rules
include $(RULES)

