# $Id: Makefile,v 1.4 2006/08/02 16:35:08 jsnelson Exp $

###### Include macro definitions

MAKEDEFS = $(builddir)/Makefile.defs
include $(MAKEDEFS)

###### Files

SOURCES= $(DBXML_SOURCES)

###### Include rules

RULES = $(builddir)/Makefile.rules
include $(RULES)
