//
//  Copyright (C) 2004-2011 by Autodesk, Inc.
//
//  This library is free software; you can redistribute it and/or
//  modify it under the terms of version 2.1 of the GNU Lesser
//  General Public License as published by the Free Software Foundation.
//
//  This library is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
//  Lesser General Public License for more details.
//
//  You should have received a copy of the GNU Lesser General Public
//  License along with this library; if not, write to the Free Software
//  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
//

// disable C4503 - decorated name length exceeded, name was truncated
#pragma warning(disable: 4503)

#include "Data/BatchPropertyCollection.cpp"
#include "Data/Byte.cpp"
#include "Data/ByteReader.cpp"
#include "Data/ByteSink.cpp"
#include "Data/ByteSource.cpp"
#include "Data/Collection.cpp"
#include "Data/DateTime.cpp"
#include "Data/MimeType.cpp"
#include "Data/NamedCollection.cpp"
#include "Data/NullableProperty.cpp"
#include "Data/Property.cpp"
#include "Data/PropertyCollection.cpp"
#include "Data/PropertyDefinition.cpp"
#include "Data/StringCollection.cpp"
#include "Data/StringProperty.cpp"

#include "Exception/ApplicationException.cpp"
#include "Exception/ArgumentOutOfRangeException.cpp"
#include "Exception/ClassNotFoundException.cpp"
#include "Exception/ConfigurationException.cpp"
#include "Exception/ConfigurationLoadFailedException.cpp"
#include "Exception/ConfigurationSaveFailedException.cpp"
#include "Exception/DateTimeException.cpp"
#include "Exception/DecryptionException.cpp"
#include "Exception/DirectoryNotFoundException.cpp"
#include "Exception/DivideByZeroException.cpp"
#include "Exception/DomainException.cpp"
#include "Exception/DuplicateDirectoryException.cpp"
#include "Exception/DuplicateFileException.cpp"
#include "Exception/DuplicateObjectException.cpp"
#include "Exception/EncryptionException.cpp"
#include "Exception/Exception.cpp"
#include "Exception/FileIoException.cpp"
#include "Exception/FileNotFoundException.cpp"
#include "Exception/GridDensityException.cpp"
#include "Exception/IndexOutOfRangeException.cpp"
#include "Exception/InvalidArgumentException.cpp"
#include "Exception/InvalidCastException.cpp"
#include "Exception/InvalidMimeTypeException.cpp"
#include "Exception/InvalidOperationException.cpp"
#include "Exception/InvalidPropertyTypeException.cpp"
#include "Exception/InvalidStreamHeaderException.cpp"
#include "Exception/IoException.cpp"
#include "Exception/LengthException.cpp"
#include "Exception/LogicException.cpp"
#include "Exception/NotFiniteNumberException.cpp"
#include "Exception/NotImplementedException.cpp"
#include "Exception/NullArgumentException.cpp"
#include "Exception/NullPropertyValueException.cpp"
#include "Exception/NullReferenceException.cpp"
#include "Exception/ObjectNotFoundException.cpp"
#include "Exception/OutOfMemoryException.cpp"
#include "Exception/OutOfRangeException.cpp"
#include "Exception/OverflowException.cpp"
#include "Exception/PlatformNotSupportedException.cpp"
#include "Exception/ResourcesException.cpp"
#include "Exception/ResourcesLoadFailedException.cpp"
#include "Exception/ResourceTagNotFoundException.cpp"
#include "Exception/RuntimeException.cpp"
#include "Exception/StreamIoException.cpp"
#include "Exception/SystemException.cpp"
#include "Exception/TemporaryFileNotAvailableException.cpp"
#include "Exception/ThirdPartyException.cpp"
#include "Exception/UnclassifiedException.cpp"
#include "Exception/UnderflowException.cpp"
#include "Exception/XmlException.cpp"
#include "Exception/XmlParserException.cpp"

#include "System/AceStreamHelper.cpp"
#include "System/ByteSourceFileImpl.cpp"
#include "System/ByteSourceMemoryImpl.cpp"
#include "System/ByteSourceSocketStreamImpl.cpp"
#include "System/ByteSourceStreamImpl.cpp"
#include "System/ClassFactory.cpp"
#include "System/Configuration.cpp"
#include "System/ConfigurationHeap.cpp"
#include "System/ConfigurationSection.cpp"
#include "System/ConfigurationSectionCollection.cpp"
#include "System/Disposable.cpp"
#include "System/DisposableCollection.cpp"
#include "System/FileUtil.cpp"
#include "System/FoundationConfigProperties.cpp"
#include "System/GuardDisposable.cpp"
#include "System/MemoryStreamHelper.cpp"
#include "System/NamedSerializable.cpp"
#include "System/Object.cpp"
#include "System/PacketParser.cpp"
#include "System/Resources.cpp"
#include "System/Serializable.cpp"
#include "System/ServerConnectionBase.cpp"
#include "System/SetLocale.cpp"
#include "System/Stream.cpp"
#include "System/StreamData.cpp"
#include "System/StreamHelper.cpp"
#include "System/StreamParser.cpp"
#include "System/StreamReader.cpp"
#include "System/StreamWriter.cpp"
#include "System/Util.cpp"
#include "System/XmlUtil.cpp"
