#----------------------------------------------------------------------------
#       Makefile,v 4.7 2003/11/17 22:07:36 dhinton Exp
#
#       Makefile for the client programs that test the ACE network services
#----------------------------------------------------------------------------

DIRS  = Logger \
        Naming \
        Tokens

#----------------------------------------------------------------------------
#       Include macros and targets
#----------------------------------------------------------------------------

include $(ACE_ROOT)/include/makeinclude/all_in_one.GNU
# DO NOT DELETE THIS LINE -- g++dep uses it.
# DO NOT PUT ANYTHING AFTER THIS LINE, IT WILL GO AWAY.



# IF YOU PUT ANYTHING HERE IT WILL GO AWAY
