#
# Makefile.bor,v 4.5 2003/12/21 10:08:34 jwillemsen Exp
#

NAMES = \
	direct_logging \
	indirect_logging

OBJFILES=$(OBJDIR)\$(NAME).obj

CFLAGS = $(ACE_CFLAGS)

CPPDIR = .

LIBFILES = $(ACE_LIB)

!include <$(ACE_ROOT)\include\makeinclude\recurse.bor>
!include <$(ACE_ROOT)\include\makeinclude\build_exe.bor>

