# $Id: Makefile,v 1.1 2004/09/28 12:11:37 awood Exp $

###### Include macro definitions

MAKEDEFS = ../../../build_unix/Makefile.defs
include $(MAKEDEFS)

###### Files

SOURCES= $(UNIT_TEST_INPUTSTREAMS_SOURCES)

###### Include rules

RULES = ../../../build_unix/Makefile.rules
include $(RULES)

