# $Id: Makefile,v 1.2 2006/06/13 19:33:45 gmf Exp $

###### Include macro definitions

MAKEDEFS = $(builddir)/Makefile.defs
include $(MAKEDEFS)

###### Files

SOURCES= $(XQTS_SOURCES)

###### Include rules

RULES = $(builddir)/Makefile.rules
include $(RULES)

